const SUPABASE_URL='https://jqrzyonpverklusjenej.supabase.co';
const SUPABASE_KEY='sb_publishable_ncZAYxw3aXlsJYtFOmjG1Q_g3fnCIQ7';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
function deviceToken(){let t=localStorage.getItem('h3_admin_device');if(!t){t=crypto.randomUUID();localStorage.setItem('h3_admin_device',t)}return t}
const adminDevice=deviceToken();
const activation=document.getElementById('activation'),dashboard=document.getElementById('dashboard'),notice=document.getElementById('notice'),entryCount=document.getElementById('entryCount'),voteCount=document.getElementById('voteCount'),allowEdit=document.getElementById('allowEdit'),entriesEl=document.getElementById('entries');
let currentPhase='closed';
function msg(text,error=false){notice.textContent=text;notice.className='notice'+(error?' error':'');notice.hidden=false;setTimeout(()=>notice.hidden=true,4500)}
function esc(v=''){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function photo(path){return `${SUPABASE_URL}/storage/v1/object/public/contest-photos/${path.split('/').map(encodeURIComponent).join('/')}`}
async function loadDashboard(){const{data,error}=await sb.rpc('admin_get_dashboard',{p_device_token:adminDevice});if(error){activation.hidden=false;dashboard.hidden=true;return false}activation.hidden=true;dashboard.hidden=false;renderDashboard(data);return true}
function renderDashboard(data){const settings=data.settings||{};currentPhase=settings.phase||'closed';entryCount.textContent=(data.entries||[]).length;voteCount.textContent=data.total_votes||0;allowEdit.checked=!!settings.allow_entry_edit;allowEdit.disabled=currentPhase!=='registration';document.querySelectorAll('[data-phase]').forEach(b=>b.classList.toggle('active',b.dataset.phase===currentPhase));entriesEl.innerHTML=(data.entries||[]).map(e=>`<div class="entry-row"><img src="${photo(e.image_path)}" alt=""><div class="entry-info"><strong>${esc(e.name)}</strong><p>${esc(e.description||'')}</p><span class="vote-pill">${e.vote_count} gł.</span></div><button class="delete-button" data-delete="${e.id}">Usuń</button></div>`).join('')||'<div class="empty">Brak zgłoszeń.</div>';entriesEl.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteEntry(b.dataset.delete))}
document.getElementById('activateButton').onclick=async function(){const code=document.getElementById('activationCode').value.trim();if(!code)return msg('Wpisz kod aktywacyjny.',true);this.disabled=true;try{const{data,error}=await sb.rpc('admin_activate_device',{p_device_token:adminDevice,p_activation_code:code});if(error)throw error;if(!data)throw new Error('Kod jest nieprawidłowy albo administrator został już aktywowany.');msg('Ten telefon jest teraz administratorem ✓');await loadDashboard()}catch(e){msg(e.message||'Aktywacja nie powiodła się.',true)}finally{this.disabled=false}};
document.querySelectorAll('[data-phase]').forEach(button=>button.onclick=async()=>{const next=button.dataset.phase;if(next===currentPhase)return;if((next==='voting'||next==='finished')&&!confirm('Ta zmiana wpłynie natychmiast na wszystkich uczestników. Kontynuować?'))return;try{const{error}=await sb.rpc('admin_update_settings',{p_device_token:adminDevice,p_phase:next,p_allow_edit:allowEdit.checked});if(error)throw error;msg('Etap konkursu zmieniony ✓');await loadDashboard()}catch(e){msg(e.message||'Nie udało się zmienić etapu.',true)}});
allowEdit.onchange=async()=>{try{const{error}=await sb.rpc('admin_update_settings',{p_device_token:adminDevice,p_phase:currentPhase,p_allow_edit:allowEdit.checked});if(error)throw error;msg(allowEdit.checked?'Edycja zgłoszeń włączona ✓':'Edycja zgłoszeń wyłączona ✓');await loadDashboard()}catch(e){allowEdit.checked=!allowEdit.checked;msg(e.message||'Nie udało się zapisać ustawienia.',true)}};
async function deleteEntry(id){if(!confirm('Usunąć to zgłoszenie? Tej operacji nie można cofnąć.'))return;try{const{error}=await sb.rpc('admin_delete_entry',{p_device_token:adminDevice,p_entry_id:id});if(error)throw error;msg('Zgłoszenie usunięte.');await loadDashboard()}catch(e){msg(e.message||'Nie udało się usunąć zgłoszenia.',true)}}
document.getElementById('refreshButton').onclick=loadDashboard;
loadDashboard();