(()=>{
const style=document.createElement('link');style.rel='stylesheet';style.href='admin-menu.css?v=5';document.head.appendChild(style);
['admin-recovery.css?v=2','admin-other.css?v=3','admin-stats.css?v=1'].forEach(href=>{const l=document.createElement('link');l.rel='stylesheet';l.href=href;document.head.appendChild(l)});
['admin-recovery.js?v=2','admin-other.js?v=3','admin-stats.js?v=2'].forEach(src=>{const s=document.createElement('script');s.src=src;document.body.appendChild(s)});
const dashboard=document.getElementById('dashboard'),menu=document.getElementById('adminMainMenu'),back=document.getElementById('adminMenuBack'),title=document.getElementById('adminPanelTitle');if(!dashboard||!menu)return;
const sections={home:['statusCard','identity','homeTabCard','publicVersionCard'],contest:['contestCard','contestSettingsCard','contestEntriesCard'],news:['newsAdminCard'],photos:['galleryAdminCard'],other:['adminOtherCard'],stats:['adminStatsCard'],admins:['superSection'],history:['auditSection']};
let activePanel=null,guard=null;
function allIds(){return Object.values(sections).flat()}
function hideAll(){allIds().forEach(id=>{const e=document.getElementById(id);if(e)e.hidden=true})}
function showMenu(){activePanel=null;hideAll();menu.hidden=false;if(back)back.hidden=true;if(title)title.textContent='Panel administratora'}
function removeGuard(){guard?.remove();guard=null}
function addGuard(){removeGuard();guard=document.createElement('div');guard.className='admin-entry-guard';guard.style.cssText='position:fixed;inset:0;z-index:2147483647;background:transparent;touch-action:none';const stop=e=>{e.preventDefault();e.stopImmediatePropagation()};['pointerdown','pointerup','click','touchstart','touchend'].forEach(t=>guard.addEventListener(t,stop,{capture:true,passive:false}));document.body.appendChild(guard);setTimeout(removeGuard,750)}
function openPanel(key,label){activePanel=key;hideAll();menu.hidden=true;if(back)back.hidden=false;if(title)title.textContent=label||'Panel';(sections[key]||[]).forEach(id=>{const e=document.getElementById(id);if(e)e.hidden=false});if(key==='stats')setTimeout(()=>window.loadAdminStats?.(),80);if(key==='other')setTimeout(()=>window.loadAdminOther?.(),80);if(key==='home')setTimeout(loadHomeTabSetting,60)}
menu.addEventListener('click',e=>{const b=e.target.closest('[data-admin-panel]');if(!b)return;openPanel(b.dataset.adminPanel,b.querySelector('strong')?.textContent||'Panel')});back?.addEventListener('click',showMenu);
window.adminMenuOpenPanel=openPanel;window.adminMenuShowMenu=showMenu;
const observer=new MutationObserver(()=>{if(!dashboard.hidden&&!activePanel&&menu.hidden===false)addGuard()});observer.observe(dashboard,{attributes:true,attributeFilter:['hidden']});
async function loadHomeTabSetting(){const card=document.getElementById('homeTabCard');if(!card)return;try{const{data,error}=await sb.rpc('admin_get_app_settings',{p_device_token:adminDevice});if(error)throw error;const value=data?.home_tab||'news';card.querySelectorAll('[data-home-tab]').forEach(b=>b.classList.toggle('active',b.dataset.homeTab===value))}catch(e){console.warn(e)}}
document.getElementById('homeTabCard')?.addEventListener('click',async e=>{const b=e.target.closest('[data-home-tab]');if(!b)return;try{const{error}=await sb.rpc('admin_set_home_tab',{p_device_token:adminDevice,p_home_tab:b.dataset.homeTab});if(error)throw error;document.querySelectorAll('[data-home-tab]').forEach(x=>x.classList.toggle('active',x===b));msg('Strona startowa zapisana ✓')}catch(err){msg(err.message||'Nie udało się zapisać.',true)}});
const publicVersionToggle=document.getElementById('publicVersionToggle');async function loadPublicVersion(){if(!publicVersionToggle)return;try{const{data,error}=await sb.rpc('admin_get_app_settings',{p_device_token:adminDevice});if(error)throw error;publicVersionToggle.checked=!!data?.show_public_version}catch(e){console.warn(e)}}publicVersionToggle?.addEventListener('change',async()=>{try{const{error}=await sb.rpc('admin_set_public_version',{p_device_token:adminDevice,p_enabled:publicVersionToggle.checked});if(error)throw error;msg(publicVersionToggle.checked?'Numer wersji widoczny ✓':'Numer wersji ukryty ✓')}catch(e){publicVersionToggle.checked=!publicVersionToggle.checked;msg(e.message||'Nie udało się zapisać.',true)}});setTimeout(loadPublicVersion,700);
(async()=>{try{const r=await fetch(`service-worker.js?v=${Date.now()}`,{cache:'no-store'}),t=await r.text(),m=t.match(/halloween-3-v(\d+)/i);if(m){const e=document.querySelector('.admin-version');if(e)e.textContent=`V${m[1]}`}}catch{}})();
showMenu();
})();