(()=>{
const list=document.getElementById('adminNewsList'),createBtn=document.getElementById('createNewsPost');if(!list||!createBtn)return;
function val(id){return document.getElementById(id)?.value?.trim()||''}
function escapeHtml(v=''){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}
async function loadAdminNews(){if(document.getElementById('dashboard')?.hidden)return;try{const{data,error}=await sb.rpc('admin_get_news',{p_device_token:adminDevice});if(error)throw error;render(data||[])}catch(e){list.innerHTML=`<div class="news-admin-empty">${escapeHtml(e.message||'Nie udało się pobrać aktualności.')}</div>`}}
function render(items){list.innerHTML=items.map((n,i)=>`<div class="news-admin-item" data-news-id="${n.id}"><div class="news-admin-top"><input class="news-icon" maxlength="12" value="${escapeHtml(n.icon||'🎃')}" aria-label="Ikona"><input class="news-title" maxlength="120" value="${escapeHtml(n.title||'')}" aria-label="Tytuł"></div><input class="news-badge" maxlength="30" value="${escapeHtml(n.badge||'')}" placeholder="Etykieta, np. WAŻNE"><textarea class="news-body" maxlength="1500" placeholder="Treść aktualności">${escapeHtml(n.body||'')}</textarea><div class="news-admin-actions"><label class="news-visible"><input class="news-active" type="checkbox" ${n.active?'checked':''}> Widoczna w aplikacji</label><div class="news-admin-order"><button class="secondary" data-news-move="up" ${i===0?'disabled':''}>↑</button><button class="secondary" data-news-move="down" ${i===items.length-1?'disabled':''}>↓</button></div><button class="secondary" data-news-save>Zapisz</button><button class="danger-button" data-news-delete>Usuń</button></div></div>`).join('')||'<div class="news-admin-empty">Brak aktualności.</div>'}
async function saveItem(row){const payload={p_device_token:adminDevice,p_news_id:row.dataset.newsId,p_title:row.querySelector('.news-title').value.trim(),p_body:row.querySelector('.news-body').value.trim(),p_icon:row.querySelector('.news-icon').value.trim()||'🎃',p_badge:row.querySelector('.news-badge').value.trim(),p_active:row.querySelector('.news-active').checked};if(!payload.p_title)return msg('Podaj tytuł aktualności.',true);const{error}=await sb.rpc('admin_update_news',payload);if(error)throw error;msg('Aktualność zapisana ✓');await loadAdminNews();await loadDashboard()}
async function moveItem(id,direction){const{error}=await sb.rpc('admin_move_news',{p_device_token:adminDevice,p_news_id:id,p_direction:direction});if(error)throw error;await loadAdminNews();await loadDashboard()}
async function deleteItem(id){if(!confirm('Usunąć tę aktualność?'))return;const{error}=await sb.rpc('admin_delete_news',{p_device_token:adminDevice,p_news_id:id});if(error)throw error;msg('Aktualność usunięta ✓');await loadAdminNews();await loadDashboard()}
list.addEventListener('click',async e=>{const row=e.target.closest('.news-admin-item');if(!row)return;try{if(e.target.closest('[data-news-save]'))await saveItem(row);else if(e.target.closest('[data-news-delete]'))await deleteItem(row.dataset.newsId);else{const m=e.target.closest('[data-news-move]');if(m)await moveItem(row.dataset.newsId,m.dataset.newsMove)}}catch(err){msg(err.message||'Nie udało się wykonać operacji.',true)}});
createBtn.onclick=async function(){const title=val('newNewsTitle');if(!title)return msg('Podaj tytuł aktualności.',true);this.disabled=true;try{const{error}=await sb.rpc('admin_create_news',{p_device_token:adminDevice,p_title:title,p_body:val('newNewsBody'),p_icon:val('newNewsIcon')||'🎃',p_badge:val('newNewsBadge')});if(error)throw error;['newNewsTitle','newNewsBody','newNewsBadge'].forEach(id=>document.getElementById(id).value='');document.getElementById('newNewsIcon').value='🎃';msg('Aktualność dodana ✓');await loadAdminNews();await loadDashboard()}catch(e){msg(e.message||'Nie udało się dodać aktualności.',true)}finally{this.disabled=false}};
document.getElementById('refreshNews')?.addEventListener('click',loadAdminNews);
const auditMap={news_post_created:'Dodano aktualność',news_post_updated:'Zmieniono aktualność',news_post_deleted:'Usunięto aktualność',news_order_changed:'Zmieniono kolejność aktualności'};function patchAudit(){document.querySelectorAll('#auditLogs .audit-row>strong').forEach(el=>{if(auditMap[el.textContent])el.textContent=auditMap[el.textContent]})}new MutationObserver(patchAudit).observe(document.getElementById('auditLogs'),{childList:true,subtree:true});
new MutationObserver(()=>{if(!document.getElementById('dashboard').hidden)loadAdminNews()}).observe(document.getElementById('dashboard'),{attributes:true,attributeFilter:['hidden']});setTimeout(loadAdminNews,500);
})();