(()=>{
const host=document.getElementById('adminOtherCard');if(!host)return;
const list=host.querySelector('#adminOtherList');
const esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
const imageUrl=path=>`${SUPABASE_URL}/storage/v1/object/public/other-images/${String(path||'').split('/').map(encodeURIComponent).join('/')}`;
let data=[];
async function load(){list.innerHTML='<div class="other-admin-empty">Ładowanie...</div>';try{const{data:d,error}=await sb.rpc('admin_get_other',{p_device_token:adminDevice});if(error)throw error;data=d||[];render()}catch(e){list.innerHTML=`<div class="other-admin-empty">${esc(e.message||'Nie udało się pobrać danych.')}</div>`}}
function itemMarkup(t,child=false){const isText=t.content_type==='text',isImage=t.content_type==='image',isMenu=t.content_type==='menu';return `<div class="other-admin-item ${child?'child':''}" data-other-admin-id="${t.id}"><div class="other-admin-type">${isText?'Tekst':isImage?'Zdjęcie':'Podmenu'}</div><div class="other-admin-head"><input data-field="icon" maxlength="12" value="${esc(t.icon||'📄')}"><input data-field="title" maxlength="100" value="${esc(t.title||'')}"></div>${isText?`<textarea data-field="body" maxlength="10000" placeholder="Treść...">${esc(t.body||'')}</textarea>`:''}${isImage?`<div class="other-admin-image">${t.image_path?`<img src="${imageUrl(t.image_path)}" alt=""><button type="button" class="secondary" data-remove-other-image>Usuń zdjęcie</button>`:''}<label class="other-admin-upload">🖼️ Wybierz zdjęcie bez kompresji<input type="file" accept="image/*" data-other-image hidden></label><div class="other-admin-note">Plik jest wysyłany w oryginalnej jakości, bez kompresji.</div></div>`:''}${isMenu?`<div class="other-admin-subcreate"><input data-new-child-icon maxlength="12" value="📄"><input data-new-child-title maxlength="100" placeholder="Nazwa podkafelka"><select data-new-child-type><option value="text">Tekst</option><option value="image">Zdjęcie</option><option value="menu">Podmenu</option></select><button type="button" class="secondary" data-add-child>Dodaj</button></div>`:''}<div class="other-admin-actions"><div class="other-admin-order"><button type="button" class="secondary" data-move-other="up">↑</button><button type="button" class="secondary" data-move-other="down">↓</button></div><button type="button" class="secondary" data-save-other>Zapisz</button><button type="button" class="danger-button" data-delete-other>Usuń</button></div></div>`}
function render(){list.innerHTML=data.map(r=>itemMarkup(r)+((r.children||[]).map(c=>itemMarkup(c,true)).join(''))).join('')||'<div class="other-admin-empty">Brak kafelków.</div>'}
async function save(row){const id=row.dataset.otherAdminId,title=row.querySelector('[data-field="title"]')?.value.trim(),icon=row.querySelector('[data-field="icon"]')?.value.trim(),body=row.querySelector('[data-field="body"]')?.value??'';let imagePath=row.dataset.pendingImagePath;if(imagePath===undefined){const img=row.querySelector('.other-admin-image img');if(img){const prefix=`${SUPABASE_URL}/storage/v1/object/public/other-images/`;imagePath=decodeURI(img.src).startsWith(prefix)?decodeURIComponent(img.src.slice(prefix.length)):null}else imagePath=null}const{error}=await sb.rpc('admin_update_other_tile',{p_device_token:adminDevice,p_tile_id:id,p_title:title,p_icon:icon,p_body:body,p_image_path:imagePath||null,p_active:true});if(error)throw error;msg('Zapisano kafelek ✓');await load()}
async function upload(row,file){if(!file)return;const path=`${row.dataset.otherAdminId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const{error}=await sb.storage.from('other-images').upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(error)throw error;row.dataset.pendingImagePath=path;let wrap=row.querySelector('.other-admin-image');wrap.querySelector('img')?.remove();const img=document.createElement('img');img.src=imageUrl(path);img.alt='Podgląd';wrap.prepend(img);msg('Zdjęcie wybrane. Kliknij Zapisz ✓')}
list.addEventListener('change',async e=>{const input=e.target.closest('[data-other-image]');if(!input)return;const row=input.closest('[data-other-admin-id]');try{await upload(row,input.files?.[0])}catch(err){msg(err.message||'Nie udało się wysłać zdjęcia.',true)}});
list.addEventListener('click',async e=>{const row=e.target.closest('[data-other-admin-id]');if(!row)return;const id=row.dataset.otherAdminId;try{if(e.target.closest('[data-save-other]'))return await save(row);if(e.target.closest('[data-delete-other]')){if(!confirm('Usunąć ten kafelek?'))return;const{error}=await sb.rpc('admin_delete_other_tile',{p_device_token:adminDevice,p_tile_id:id});if(error)throw error;msg('Kafelek usunięty ✓');return await load()}if(constMove=e.target.closest('[data-move-other]')){const{error}=await sb.rpc('admin_move_other_tile',{p_device_token:adminDevice,p_tile_id:id,p_direction:constMove.dataset.moveOther});if(error)throw error;return await load()}if(e.target.closest('[data-remove-other-image]')){row.dataset.pendingImagePath='';row.querySelector('.other-admin-image img')?.remove();msg('Zdjęcie oznaczone do usunięcia. Kliknij Zapisz.');return}if(e.target.closest('[data-add-child]')){const title=row.querySelector('[data-new-child-title]').value.trim(),icon=row.querySelector('[data-new-child-icon]').value.trim(),type=row.querySelector('[data-new-child-type]').value;if(!title)return msg('Podaj nazwę podkafelka.',true);const{error}=await sb.rpc('admin_create_other_tile',{p_device_token:adminDevice,p_parent_id:id,p_title:title,p_icon:icon,p_content_type:type});if(error)throw error;msg('Dodano podkafelek ✓');return await load()}}catch(err){msg(err.message||'Operacja nie powiodła się.',true)}});
host.querySelector('#createOtherTile').onclick=async()=>{const title=host.querySelector('#newOtherTitle').value.trim(),icon=host.querySelector('#newOtherIcon').value.trim(),type=host.querySelector('#newOtherType').value;if(!title)return msg('Podaj nazwę kafelka.',true);try{const{error}=await sb.rpc('admin_create_other_tile',{p_device_token:adminDevice,p_parent_id:null,p_title:title,p_icon:icon,p_content_type:type});if(error)throw error;host.querySelector('#newOtherTitle').value='';msg('Dodano kafelek ✓');await load()}catch(e){msg(e.message||'Nie udało się dodać kafelka.',true)}};
host.querySelector('#refreshOther').onclick=load;
window.loadAdminOther=load;
load();
})();