(()=>{
const host=document.getElementById('adminOtherCard');if(!host)return;
const esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
const imageUrl=path=>`${SUPABASE_URL}/storage/v1/object/public/other-images/${String(path||'').split('/').map(encodeURIComponent).join('/')}`;
let data=[],currentId=null,editStack=[];
host.innerHTML=`<div class="other-admin-browser"><div class="list-head"><div><h2>Inne</h2><p class="small">Wybierz kafelek, aby go edytować.</p></div><button id="refreshOther" class="secondary">Odśwież</button></div><div id="adminOtherTiles" class="other-admin-tiles"></div></div><div id="adminOtherEditor" class="other-admin-editor" hidden></div><button id="addOtherFloating" class="other-admin-fab" type="button" aria-label="Dodaj kafelek">+</button><div id="otherAddModal" class="other-admin-modal" hidden><div class="other-admin-modal-card"><div class="other-admin-modal-head"><h3>Nowy kafelek</h3><button type="button" class="other-admin-modal-close" aria-label="Zamknij">×</button></div><label>Ikona<input id="modalOtherIcon" maxlength="12" value="📄"></label><label>Nazwa<input id="modalOtherTitle" maxlength="100" placeholder="Nazwa kafelka"></label><label>Folder nadrzędny<select id="modalOtherParent"><option value="">Brak, kafelek główny</option></select></label><button id="modalCreateOther" class="primary" type="button">DODAJ KAFELEK</button></div></div>`;
const tiles=host.querySelector('#adminOtherTiles'),editor=host.querySelector('#adminOtherEditor'),browser=host.querySelector('.other-admin-browser'),modal=host.querySelector('#otherAddModal');
function allTiles(){const out=[];for(const r of data){out.push(r);for(const c of(r.children||[]))out.push(c)}return out}
function parentOf(id){return data.find(r=>(r.children||[]).some(c=>c.id===id))||null}
function findTile(id){return allTiles().find(x=>x.id===id)||null}
function tileCard(t){const hasText=!!(t.body||'').trim(),hasImage=!!t.image_path,hasChildren=!!(t.children||[]).length;const bits=[hasText?'tekst':'',hasImage?'zdjęcie':'',hasChildren?`${t.children.length} podkaf.`:''].filter(Boolean).join(' • ')||'pusty';return `<button type="button" class="other-admin-tile" data-edit-other="${t.id}"><span class="other-admin-tile-icon">${esc(t.icon||'📄')}</span><span><strong>${esc(t.title)}</strong><small>${bits}</small></span><span class="other-admin-chevron">›</span></button>`}
function renderTiles(){browser.hidden=false;editor.hidden=true;currentId=null;editStack=[];tiles.innerHTML=data.map(tileCard).join('')||'<div class="other-admin-empty">Brak kafelków.</div>';fillParentSelect();document.body.classList.remove('other-editor-open')}
function fillParentSelect(){const sel=host.querySelector('#modalOtherParent');sel.innerHTML='<option value="">Brak, kafelek główny</option>'+data.map(r=>`<option value="${r.id}">${esc(r.title)}</option>`).join('')}
function openEditor(id,push=true){const t=findTile(id);if(!t)return;if(push&&currentId)editStack.push(currentId);currentId=id;browser.hidden=true;editor.hidden=false;document.body.classList.add('other-editor-open');const parent=parentOf(id);const parentOptions='<option value="">Brak, kafelek główny</option>'+data.filter(r=>r.id!==id).map(r=>`<option value="${r.id}" ${parent?.id===r.id?'selected':''}>${esc(r.title)}</option>`).join('');const childCards=(t.children||[]).length?`<div class="other-admin-children"><div class="other-admin-section-title">Podkafelki</div><div class="other-admin-tiles">${t.children.map(tileCard).join('')}</div></div>`:'';editor.innerHTML=`<div class="other-admin-editor-shell"><div class="other-admin-editor-top"><button class="other-admin-editor-back" type="button">← Wróć</button><strong>${esc(t.title)}</strong></div><div class="other-admin-edit-card"><div class="other-admin-edit-head"><div class="other-admin-edit-icon">${esc(t.icon||'📄')}</div><div><h3>${esc(t.title)}</h3><p>Edytuj zawartość kafelka.</p></div></div><label>Ikona<input data-field="icon" maxlength="12" value="${esc(t.icon||'📄')}"></label><label>Nazwa<input data-field="title" maxlength="100" value="${esc(t.title||'')}"></label><label>Folder nadrzędny<select data-field="parent">${parentOptions}</select></label><label>Tekst<textarea data-field="body" maxlength="10000" rows="9" placeholder="Wpisz treść. Jeśli pole zostanie puste, użytkownik go nie zobaczy.">${esc(t.body||'')}</textarea></label><div class="other-admin-image-block"><strong>Obraz</strong>${t.image_path?`<img src="${imageUrl(t.image_path)}" alt="Podgląd"><button type="button" class="secondary" data-remove-image>Usuń obraz</button>`:''}<label class="other-admin-upload">🖼️ Dodaj obraz bez kompresji<input type="file" accept="image/*" data-image-input hidden></label><small>Obraz zostanie wysłany w oryginalnej jakości.</small></div>${childCards}<div class="other-admin-edit-actions"><div class="other-admin-order"><button type="button" class="secondary" data-move="up">↑</button><button type="button" class="secondary" data-move="down">↓</button></div><button type="button" class="primary" data-save>Zapisz</button><button type="button" class="danger-button" data-delete>Usuń</button></div></div></div>`;editor.dataset.pendingImage='';editor.dataset.removeImage='0';editor.scrollTop=0}
function goBackEditor(){if(editStack.length){const prev=editStack.pop();openEditor(prev,false)}else renderTiles()}
async function load(){tiles.innerHTML='<div class="other-admin-empty">Ładowanie...</div>';try{const{data:d,error}=await sb.rpc('admin_get_other',{p_device_token:adminDevice});if(error)throw error;data=d||[];if(currentId&&findTile(currentId))openEditor(currentId,false);else renderTiles()}catch(e){tiles.innerHTML=`<div class="other-admin-empty">${esc(e.message||'Nie udało się pobrać danych.')}</div>`}}
async function upload(file){if(!file||!currentId)return;const path=`${currentId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const{error}=await sb.storage.from('other-images').upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(error)throw error;editor.dataset.pendingImage=path;editor.dataset.removeImage='0';const block=editor.querySelector('.other-admin-image-block');block.querySelector('img')?.remove();const img=document.createElement('img');img.src=imageUrl(path);img.alt='Podgląd';block.insertBefore(img,block.querySelector('[data-remove-image],.other-admin-upload'));if(!block.querySelector('[data-remove-image]')){const b=document.createElement('button');b.type='button';b.className='secondary';b.dataset.removeImage='';b.textContent='Usuń obraz';block.insertBefore(b,block.querySelector('.other-admin-upload'))}msg('Obraz wybrany. Kliknij Zapisz ✓')}
async function save(){const t=findTile(currentId);if(!t)return;const title=editor.querySelector('[data-field="title"]').value.trim(),icon=editor.querySelector('[data-field="icon"]').value.trim(),body=editor.querySelector('[data-field="body"]').value,parent=editor.querySelector('[data-field="parent"]').value||null;if(!title)return msg('Podaj nazwę kafelka.',true);let imagePath=t.image_path||null;if(editor.dataset.removeImage==='1')imagePath=null;if(editor.dataset.pendingImage)imagePath=editor.dataset.pendingImage;const{error}=await sb.rpc('admin_update_other_tile',{p_device_token:adminDevice,p_tile_id:currentId,p_title:title,p_icon:icon,p_body:body,p_image_path:imagePath,p_active:true});if(error)throw error;const currentParent=parentOf(currentId)?.id||null;if(parent!==currentParent){const{error:pe}=await sb.rpc('admin_set_other_parent',{p_device_token:adminDevice,p_tile_id:currentId,p_parent_id:parent});if(pe)throw pe}msg('Zapisano kafelek ✓');await load()}
host.addEventListener('click',async e=>{const editBtn=e.target.closest('[data-edit-other]');if(editBtn)return openEditor(editBtn.dataset.editOther,true);if(e.target.closest('.other-admin-editor-back'))return goBackEditor();if(e.target.closest('#refreshOther'))return load();if(e.target.closest('#addOtherFloating')){fillParentSelect();const current=findTile(currentId);const sel=host.querySelector('#modalOtherParent');if(current&&data.some(r=>r.id===current.id))sel.value=current.id;modal.hidden=false;return}if(e.target.closest('.other-admin-modal-close')){modal.hidden=true;return}if(e.target===modal){modal.hidden=true;return}try{if(e.target.closest('#modalCreateOther')){const title=host.querySelector('#modalOtherTitle').value.trim(),icon=host.querySelector('#modalOtherIcon').value.trim(),parent=host.querySelector('#modalOtherParent').value||null;if(!title)return msg('Podaj nazwę kafelka.',true);const{error}=await sb.rpc('admin_create_other_tile',{p_device_token:adminDevice,p_parent_id:parent,p_title:title,p_icon:icon,p_content_type:'text'});if(error)throw error;host.querySelector('#modalOtherTitle').value='';modal.hidden=true;msg('Dodano kafelek ✓');return await load()}if(e.target.closest('[data-remove-image]')){editor.dataset.removeImage='1';editor.dataset.pendingImage='';editor.querySelector('.other-admin-image-block img')?.remove();e.target.closest('[data-remove-image]')?.remove();msg('Obraz zostanie usunięty po zapisaniu.');return}if(e.target.closest('[data-save]'))return await save();if(e.target.closest('[data-delete]')){if(!confirm('Usunąć ten kafelek?'))return;const deleting=currentId;const{error}=await sb.rpc('admin_delete_other_tile',{p_device_token:adminDevice,p_tile_id:deleting});if(error)throw error;msg('Kafelek usunięty ✓');currentId=null;if(editStack.length){const prev=editStack.pop();await load();if(findTile(prev))openEditor(prev,false);else renderTiles()}else await load();return}const move=e.target.closest('[data-move]');if(move){const{error}=await sb.rpc('admin_move_other_tile',{p_device_token:adminDevice,p_tile_id:currentId,p_direction:move.dataset.move});if(error)throw error;return await load()}}catch(err){msg(err.message||'Operacja nie powiodła się.',true)}});
host.addEventListener('change',async e=>{const input=e.target.closest('[data-image-input]');if(!input)return;try{await upload(input.files?.[0])}catch(err){msg(err.message||'Nie udało się wysłać obrazu.',true)}});
window.loadAdminOther=load;load();
})();