const SUPABASE_URL='https://jqrzyonpverklusjenej.supabase.co';
const SUPABASE_KEY='sb_publishable_ncZAYxw3aXlsJYtFOmjG1Q_g3fnCIQ7';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
function readCookie(name){const p=document.cookie.split('; ').find(x=>x.startsWith(name+'='));return p?decodeURIComponent(p.slice(name.length+1)):null}
function persistAdminToken(t){try{localStorage.setItem('h3_admin_device',t);localStorage.setItem('h3_admin_device_backup',t)}catch{};document.cookie=`h3_admin_device_backup=${encodeURIComponent(t)}; Max-Age=31536000; Path=/Halloween-3.0/; SameSite=Lax; Secure`}
function deviceToken(){let t=null;try{t=localStorage.getItem('h3_admin_device')||localStorage.getItem('h3_admin_device_backup')}catch{};t=t||readCookie('h3_admin_device_backup');if(!t)t=crypto.randomUUID();persistAdminToken(t);return t}
const adminDevice=deviceToken();
const activation=document.getElementById('activation'),dashboard=document.getElementById('dashboard'),notice=document.getElementById('notice'),entryCount=document.getElementById('entryCount'),voteCount=document.getElementById('voteCount'),allowEdit=document.getElementById('allowEdit'),entriesEl=document.getElementById('entries'),identity=document.getElementById('identity'),superSection=document.getElementById('superSection'),adminDevices=document.getElementById('adminDevices'),adminInvites=document.getElementById('adminInvites'),auditLogs=document.getElementById('auditLogs'),adminLimit=document.getElementById('adminLimit'),generatedCode=document.getElementById('generatedCode'),galleryTiles=document.getElementById('galleryTiles');
let currentPhase='closed',currentSelf=null;
function msg(text,error=false){notice.textContent=text;notice.className='notice'+(error?' error':'');notice.hidden=false;setTimeout(()=>notice.hidden=true,5000)}
function esc(v=''){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}
function photo(path){return `${SUPABASE_URL}/storage/v1/object/public/contest-photos/${String(path||'').split('/').map(encodeURIComponent).join('/')}`}
function galleryPhoto(path){return `${SUPABASE_URL}/storage/v1/object/public/admin-gallery/${String(path||'').split('/').map(encodeURIComponent).join('/')}`}
function fmtDate(v){if(!v)return '—';try{return new Intl.DateTimeFormat('pl-PL',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch{return v}}
function actionLabel(a){return({admin_activated:'Aktywacja administratora',admin_invite_created:'Utworzono kod administratora',admin_invite_revoked:'Unieważniono kod administratora',admin_removed:'Usunięto administratora',admin_limit_changed:'Zmieniono limit administratorów',admin_name_changed:'Zmieniono nazwę administratora',super_admin_access_recovered:'Odzyskano dostęp Super Admina',contest_settings_changed:'Zmieniono ustawienia konkursu',contest_entry_deleted:'Usunięto zgłoszenie',gallery_folder_created:'Utworzono folder zdjęć',gallery_folder_deleted:'Usunięto folder zdjęć',gallery_photo_added:'Dodano zdjęcie',gallery_photo_deleted:'Usunięto zdjęcie',gallery_order_changed:'Zmieniono kolejność kafelków',google_album_changed:'Zmieniono link Google Zdjęcia'})[a]||a}
async function activateWithCode(code){const{data,error}=await sb.rpc('admin_activate_access',{p_device_token:adminDevice,p_activation_code:code});if(error)throw error;return data}
async function recoverWithCode(code){const{data,error}=await sb.rpc('admin_recover_super_access',{p_device_token:adminDevice,p_recovery_code:code});if(error)throw error;persistAdminToken(adminDevice);return data}
async function loadDashboard(){persistAdminToken(adminDevice);const{data,error}=await sb.rpc('admin_get_dashboard',{p_device_token:adminDevice});if(error){activation.hidden=false;dashboard.hidden=true;return false}activation.hidden=true;dashboard.hidden=false;renderDashboard(data);await loadGallery();return true}
function renderDashboard(data){const settings=data.settings||{};currentSelf=data.self||null;currentPhase=settings.phase||'closed';identity.innerHTML=`<div>Zalogowano jako <strong>${esc(currentSelf?.display_name||'Administrator')}</strong></div><span class="role-badge">${currentSelf?.role==='super_admin'?'SUPER ADMIN':'ADMIN'}</span>`;entryCount.textContent=(data.entries||[]).length;voteCount.textContent=data.total_votes||0;allowEdit.checked=!!settings.allow_entry_edit;allowEdit.disabled=currentPhase!=='registration';document.querySelectorAll('[data-phase]').forEach(b=>b.classList.toggle('active',b.dataset.phase===currentPhase));entriesEl.innerHTML=(data.entries||[]).map(e=>`<div class="entry-row"><img src="${photo(e.image_path)}" alt=""><div class="entry-info"><strong>${esc(e.name)}</strong><p>${esc(e.description||'')}</p><span class="vote-pill">${e.vote_count} gł.</span></div><button class="delete-button" data-delete="${e.id}">Usuń</button></div>`).join('')||'<div class="empty">Brak zgłoszeń.</div>';entriesEl.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteEntry(b.dataset.delete));renderAudit(data.audit_logs||[]);renderSuper(data.admin_management)}
function renderAudit(logs){auditLogs.innerHTML=logs.map(l=>`<div class="audit-row"><strong>${esc(actionLabel(l.action))}</strong><div class="audit-meta"><span class="audit-actor">${esc(l.admin_name)}</span> • ${esc(fmtDate(l.created_at))}</div><p>${auditDetails(l)}</p></div>`).join('')||'<div class="empty">Brak zapisanych zmian.</div>'}
function auditDetails(l){const d=l.details||{};if(l.action==='contest_settings_changed')return `Etap: ${esc(d.from_phase||'—')} → ${esc(d.to_phase||'—')}, edycja zgłoszeń: ${d.to_allow_edit?'włączona':'wyłączona'}`;if(l.action==='contest_entry_deleted')return `Zgłoszenie: ${esc(d.entry_name||'')}`;if(l.action==='admin_invite_created'||l.action==='admin_invite_revoked'||l.action==='admin_removed')return `Administrator: ${esc(d.display_name||'')}`;if(l.action==='admin_limit_changed')return `Nowy limit: ${esc(d.max_admins)}`;if(l.action==='admin_activated')return `Rola: ${esc(d.role==='super_admin'?'super administrator':'administrator')}`;if(l.action==='admin_name_changed')return `Nazwa: ${esc(d.from||'')} → ${esc(d.to||'')}`;if(l.action==='gallery_folder_created'||l.action==='gallery_folder_deleted')return `Folder: ${esc(d.title||'')}`;if(l.action==='gallery_photo_added'||l.action==='gallery_photo_deleted')return `Folder: ${esc(d.folder||'')}`;return ''}
function renderSuper(m){const isSuper=!!m;superSection.hidden=!isSuper;if(!isSuper)return;const ownName=document.getElementById('superAdminName');if(ownName&&document.activeElement!==ownName)ownName.value=currentSelf?.display_name||'';adminLimit.value=m.max_admins||3;adminDevices.innerHTML=(m.devices||[]).map(d=>`<div class="admin-row ${d.active?'':'inactive'}"><div><div class="admin-name">${esc(d.display_name)} ${d.role==='super_admin'?'<span class="super-badge">SUPER</span>':''}</div><div class="admin-meta">${d.active?'Aktywny':'Nieaktywny'} • aktywacja: ${esc(fmtDate(d.activated_at))}<br>ostatnio: ${esc(fmtDate(d.last_seen_at))}</div></div>${d.active&&d.role!=='super_admin'?`<button class="danger-button" data-remove-admin="${d.id}">Usuń dostęp</button>`:''}</div>`).join('')||'<div class="empty">Brak urządzeń.</div>';adminDevices.querySelectorAll('[data-remove-admin]').forEach(b=>b.onclick=()=>removeAdmin(b.dataset.removeAdmin));adminInvites.innerHTML=(m.invites||[]).map(i=>`<div class="admin-row ${i.used_at||i.revoked_at?'inactive':''}"><div><div class="admin-name">${esc(i.display_name)}</div><div class="admin-meta">${i.used_at?'Użyty '+fmtDate(i.used_at):i.revoked_at?'Unieważniony '+fmtDate(i.revoked_at):'Oczekuje na użycie'}<br>utworzony: ${esc(fmtDate(i.created_at))}</div></div>${!i.used_at&&!i.revoked_at?`<button class="danger-button" data-revoke-invite="${i.id}">Unieważnij</button>`:''}</div>`).join('')||'<div class="empty">Brak kodów.</div>';adminInvites.querySelectorAll('[data-revoke-invite]').forEach(b=>b.onclick=()=>revokeInvite(b.dataset.revokeInvite))}
async function compressImage(file){const img=await createImageBitmap(file),max=1800,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return new Promise(r=>canvas.toBlob(r,'image/jpeg',.84))}
async function loadGallery(){const{data,error}=await sb.rpc('admin_get_gallery',{p_device_token:adminDevice});if(error)return msg(error.message||'Nie udało się pobrać galerii.',true);renderGallery(data||[])}
function renderGallery(tiles){const google=tiles.find(t=>t.type==='google');document.getElementById('googleAlbumUrl').value=google?.google_url||'';galleryTiles.innerHTML=tiles.map(t=>`<div class="gallery-admin-tile"><div class="gallery-tile-head"><div><strong>${esc(t.title)}</strong><small>${t.type==='google'?'Album Google Zdjęcia':`${(t.photos||[]).length} zdjęć`}</small></div><div class="order-buttons"><button data-move="up" data-tile="${t.id}">↑</button><button data-move="down" data-tile="${t.id}">↓</button></div></div>${t.type==='folder'?`<label class="gallery-upload">Dodaj zdjęcia<input type="file" accept="image/*" multiple data-upload="${t.id}" hidden></label><div class="gallery-photo-grid">${(t.photos||[]).map(p=>`<div class="gallery-thumb"><img src="${galleryPhoto(p.image_path)}" alt=""><button data-delete-photo="${p.id}" title="Usuń">×</button></div>`).join('')}</div><button class="danger-button full" data-delete-folder="${t.id}">Usuń folder</button>`:`<div class="admin-meta">${t.google_url?esc(t.google_url):'Link nieaktywny'}</div>`}</div>`).join('')||'<div class="empty">Brak kafelków w galerii.</div>';galleryTiles.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>moveTile(b.dataset.tile,b.dataset.move));galleryTiles.querySelectorAll('[data-upload]').forEach(i=>i.onchange=e=>uploadGalleryPhotos(i.dataset.upload,[...e.target.files]));galleryTiles.querySelectorAll('[data-delete-photo]').forEach(b=>b.onclick=()=>deleteGalleryPhoto(b.dataset.deletePhoto));galleryTiles.querySelectorAll('[data-delete-folder]').forEach(b=>b.onclick=()=>deleteGalleryFolder(b.dataset.deleteFolder))}
async function uploadGalleryPhotos(tileId,files){if(!files.length)return;msg(`Dodawanie ${files.length} zdjęć...`);try{for(const file of files){const blob=await compressImage(file);const path=`${tileId}/${crypto.randomUUID()}.jpg`;const{error:u}=await sb.storage.from('admin-gallery').upload(path,blob,{contentType:'image/jpeg',upsert:false});if(u)throw u;const{error}=await sb.rpc('admin_add_gallery_photo',{p_device_token:adminDevice,p_tile_id:tileId,p_image_path:path,p_caption:''});if(error)throw error}msg('Zdjęcia dodane ✓');await loadDashboard()}catch(e){msg(e.message||'Nie udało się dodać zdjęć.',true)}}
async function moveTile(id,direction){const{error}=await sb.rpc('admin_move_gallery_tile',{p_device_token:adminDevice,p_tile_id:id,p_direction:direction});if(error)return msg(error.message,true);await loadGallery()}
async function deleteGalleryPhoto(id){if(!confirm('Usunąć to zdjęcie z galerii?'))return;const{error}=await sb.rpc('admin_delete_gallery_photo',{p_device_token:adminDevice,p_photo_id:id});if(error)return msg(error.message,true);msg('Zdjęcie usunięte ✓');await loadDashboard()}
async function deleteGalleryFolder(id){if(!confirm('Usunąć cały folder i wszystkie zdjęcia z widoku aplikacji?'))return;const{error}=await sb.rpc('admin_delete_gallery_folder',{p_device_token:adminDevice,p_tile_id:id});if(error)return msg(error.message,true);msg('Folder usunięty ✓');await loadDashboard()}
document.getElementById('createFolder').onclick=async()=>{const title=document.getElementById('newFolderTitle').value.trim();if(!title)return msg('Podaj nazwę folderu.',true);const{error}=await sb.rpc('admin_create_gallery_folder',{p_device_token:adminDevice,p_title:title});if(error)return msg(error.message,true);document.getElementById('newFolderTitle').value='';msg('Folder utworzony ✓');await loadDashboard()};
document.getElementById('saveGoogleAlbum').onclick=async()=>{const url=document.getElementById('googleAlbumUrl').value.trim();const{error}=await sb.rpc('admin_set_google_album',{p_device_token:adminDevice,p_url:url});if(error)return msg(error.message,true);msg(url?'Link zapisany ✓':'Link wyłączony ✓');await loadDashboard()};
document.getElementById('refreshGallery').onclick=loadGallery;
document.getElementById('activateButton').onclick=async function(){const code=document.getElementById('activationCode').value.trim();if(!code)return msg('Wpisz kod aktywacyjny.',true);this.disabled=true;try{let data;try{data=await activateWithCode(code)}catch{data=await recoverWithCode(code)}persistAdminToken(adminDevice);msg(`Aktywowano: ${data.display_name} ✓`);document.getElementById('activationCode').value='';await loadDashboard()}catch(e){msg(e.message||'Aktywacja nie powiodła się.',true)}finally{this.disabled=false}};
document.getElementById('upgradeButton').onclick=async function(){const code=document.getElementById('upgradeCode').value.trim();if(!code)return msg('Wpisz kod uprawnień.',true);this.disabled=true;try{const data=await activateWithCode(code);persistAdminToken(adminDevice);msg(`Uprawnienia zmienione: ${data.role==='super_admin'?'Super Administrator':'Administrator'} ✓`);document.getElementById('upgradeCode').value='';await loadDashboard()}catch(e){msg(e.message||'Nie udało się użyć kodu.',true)}finally{this.disabled=false}};
document.querySelectorAll('[data-phase]').forEach(button=>button.onclick=async()=>{const next=button.dataset.phase;if(next===currentPhase)return;if((next==='voting'||next==='finished')&&!confirm('Ta zmiana wpłynie natychmiast na wszystkich uczestników. Kontynuować?'))return;try{const{error}=await sb.rpc('admin_update_settings',{p_device_token:adminDevice,p_phase:next,p_allow_edit:allowEdit.checked});if(error)throw error;msg('Etap konkursu zmieniony ✓');await loadDashboard()}catch(e){msg(e.message||'Nie udało się zmienić etapu.',true)}});
allowEdit.onchange=async()=>{try{const{error}=await sb.rpc('admin_update_settings',{p_device_token:adminDevice,p_phase:currentPhase,p_allow_edit:allowEdit.checked});if(error)throw error;msg(allowEdit.checked?'Edycja zgłoszeń włączona ✓':'Edycja zgłoszeń wyłączona ✓');await loadDashboard()}catch(e){allowEdit.checked=!allowEdit.checked;msg(e.message||'Nie udało się zapisać ustawienia.',true)}};
async function deleteEntry(id){if(!confirm('Usunąć to zgłoszenie? Tej operacji nie można cofnąć.'))return;try{const{error}=await sb.rpc('admin_delete_entry',{p_device_token:adminDevice,p_entry_id:id});if(error)throw error;msg('Zgłoszenie usunięte.');await loadDashboard()}catch(e){msg(e.message||'Nie udało się usunąć zgłoszenia.',true)}}
document.getElementById('saveSuperAdminName').onclick=async function(){const name=document.getElementById('superAdminName').value.trim();if(!name)return msg('Podaj nazwę.',true);this.disabled=true;try{const{data,error}=await sb.rpc('admin_rename_self',{p_device_token:adminDevice,p_new_name:name});if(error)throw error;msg(`Nazwa zmieniona na: ${data.display_name} ✓`);await loadDashboard()}catch(e){msg(e.message||'Nie udało się zmienić nazwy.',true)}finally{this.disabled=false}};
document.getElementById('createInvite').onclick=async function(){const name=document.getElementById('newAdminName').value.trim();if(!name)return msg('Podaj nazwę administratora.',true);this.disabled=true;try{const{data,error}=await sb.rpc('admin_create_invite',{p_device_token:adminDevice,p_display_name:name});if(error)throw error;generatedCode.hidden=false;generatedCode.innerHTML=`Kod dla <strong>${esc(name)}</strong>:<br>${esc(data)}<br><small>Zapisz lub przekaż go teraz. Kod jest jednorazowy.</small>`;document.getElementById('newAdminName').value='';msg('Kod administratora utworzony ✓');await loadDashboard()}catch(e){msg(e.message||'Nie udało się utworzyć kodu.',true)}finally{this.disabled=false}};
document.getElementById('saveLimit').onclick=async function(){const n=Number(adminLimit.value);if(!Number.isInteger(n))return msg('Podaj prawidłowy limit.',true);try{const{error}=await sb.rpc('admin_set_limit',{p_device_token:adminDevice,p_max_admins:n});if(error)throw error;msg('Limit administratorów zapisany ✓');await loadDashboard()}catch(e){msg(e.message||'Nie udało się zmienić limitu.',true)}};
async function removeAdmin(id){if(!confirm('Usunąć dostęp tego administratora? Zwolni to jedno miejsce.'))return;try{const{error}=await sb.rpc('admin_remove_device',{p_device_token:adminDevice,p_admin_id:id});if(error)throw error;msg('Dostęp administratora usunięty ✓');await loadDashboard()}catch(e){msg(e.message||'Nie udało się usunąć administratora.',true)}}
async function revokeInvite(id){if(!confirm('Unieważnić ten kod aktywacyjny?'))return;try{const{error}=await sb.rpc('admin_revoke_invite',{p_device_token:adminDevice,p_invite_id:id});if(error)throw error;msg('Kod unieważniony ✓');await loadDashboard()}catch(e){msg(e.message||'Nie udało się unieważnić kodu.',true)}}
document.getElementById('refreshButton').onclick=loadDashboard;
loadDashboard();