(()=>{
const dashboard=document.getElementById('dashboard');if(!dashboard)return;
const menu=()=>document.querySelector('.admin-menu');
function fmt(bytes){const n=Number(bytes||0);if(n<1024)return `${n} B`;if(n<1024**2)return `${(n/1024).toFixed(1)} KB`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} MB`;return `${(n/1024**3).toFixed(2)} GB`}
function pct(a,b){return b?Math.min(100,Math.max(0,Number(a||0)/Number(b)*100)):0}
function prettyBucket(id){return ({'admin-gallery':'Galeria zdjęć','contest-photos':'Zdjęcia konkursowe','news-images':'Zdjęcia aktualności','other-images':'Obrazy w sekcji Inne'})[id]||id}
let tile=null,panel=null;
function ensure(){const m=menu();if(!m||tile)return;tile=document.createElement('button');tile.className='admin-menu-tile';tile.dataset.adminOpen='disk';tile.innerHTML='<span class="admin-menu-icon">💾</span><span><span class="admin-menu-title">Dysk</span><span class="admin-menu-desc">Miejsce zajęte przez bazę i zdjęcia</span></span>';m.appendChild(tile);
panel=document.createElement('div');panel.className='admin-function-panel';panel.dataset.adminPanel='disk';panel.innerHTML='<div class="admin-function-head"><button class="admin-function-back admin-disk-back" type="button" aria-label="Wróć">←</button><h2 class="admin-function-heading">Dysk</h2></div><section class="card"><h2>Wykorzystanie miejsca</h2><p class="small">Aktualne zużycie projektu Supabase.</p><div id="adminDiskContent">Ładowanie...</div><button id="adminDiskRefresh" class="secondary admin-disk-refresh" type="button">Odśwież</button></section>';dashboard.appendChild(panel);
tile.addEventListener('click',e=>{e.stopImmediatePropagation();m.hidden=true;document.querySelectorAll('.admin-function-panel').forEach(p=>p.classList.toggle('active',p===panel));history.replaceState(null,'','#admin-disk');load()});panel.querySelector('.admin-disk-back').onclick=e=>{e.stopPropagation();panel.classList.remove('active');m.hidden=false;history.replaceState(null,'',location.pathname+location.search);window.scrollTo({top:0,behavior:'smooth'})};panel.querySelector('#adminDiskRefresh').onclick=load}
async function load(){const host=document.getElementById('adminDiskContent');if(!host)return;host.textContent='Ładowanie...';try{const{data,error}=await sb.rpc('admin_get_storage_stats',{p_device_token:adminDevice});if(error)throw error;const s=data||{},sp=pct(s.storage_used_bytes,s.storage_limit_bytes),dp=pct(s.database_used_bytes,s.database_limit_bytes);host.innerHTML=`<div class="admin-disk-grid"><div class="admin-disk-card"><h3>📸 Zdjęcia i pliki</h3><div class="admin-disk-number">${fmt(s.storage_used_bytes)}</div><div class="admin-disk-sub">z ${fmt(s.storage_limit_bytes)} • zostało ${fmt(s.storage_remaining_bytes)}</div><div class="admin-disk-bar"><span style="width:${sp}%"></span></div><div class="admin-disk-sub">${sp.toFixed(2)}% wykorzystane</div></div><div class="admin-disk-card"><h3>🗄️ Baza aplikacji</h3><div class="admin-disk-number">${fmt(s.database_used_bytes)}</div><div class="admin-disk-sub">z ${fmt(s.database_limit_bytes)} • zostało ${fmt(s.database_remaining_bytes)}</div><div class="admin-disk-bar"><span style="width:${dp}%"></span></div><div class="admin-disk-sub">${dp.toFixed(2)}% wykorzystane</div></div></div><div class="admin-disk-breakdown">${(s.buckets||[]).map(b=>`<div class="admin-disk-row"><strong>${prettyBucket(b.bucket)}</strong><span>${fmt(b.bytes)}</span></div>`).join('')||'<div class="admin-disk-row"><strong>Brak plików</strong><span>0 B</span></div>'}</div><div class="admin-disk-note">Plan: ${s.plan||'Free'}. Limit plików i limit bazy danych są liczone osobno.</div>`}catch(e){host.textContent=e.message||'Nie udało się pobrać danych.'}}
function watch(){ensure();const role=document.querySelector('.role-badge')?.textContent||'';if(tile)tile.hidden=/FOTOGRAF/i.test(role)}new MutationObserver(watch).observe(dashboard,{subtree:true,childList:true,attributes:true});setTimeout(watch,300);
})();