(()=>{
const dashboard=document.getElementById('dashboard');if(!dashboard)return;
const menu=()=>document.querySelector('.admin-menu');
const GITHUB_REPO_API='https://api.github.com/repos/StanleyRepair/Halloween-3.0';
const GITHUB_REPO_LIMIT=1024**3;
function fmt(bytes){const n=Number(bytes||0);if(n<1024)return `${n} B`;if(n<1024**2)return `${(n/1024).toFixed(1)} KB`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} MB`;return `${(n/1024**3).toFixed(2)} GB`}
function pct(a,b){return b?Math.min(100,Math.max(0,Number(a||0)/Number(b)*100)):0}
function prettyBucket(id){return ({'admin-gallery':'Galeria zdjęć','contest-photos':'Zdjęcia konkursowe','news-images':'Zdjęcia aktualności','other-images':'Obrazy w sekcji Inne'})[id]||id}
let tile=null,panel=null;
function ensure(){const m=menu();if(!m||tile)return;tile=document.createElement('button');tile.className='admin-menu-tile';tile.dataset.adminOpen='disk';tile.innerHTML='<span class="admin-menu-icon">💾</span><span><span class="admin-menu-title">Dysk</span><span class="admin-menu-desc">Miejsce zajęte przez aplikację, bazę i zdjęcia</span></span>';m.appendChild(tile);
panel=document.createElement('div');panel.className='admin-function-panel';panel.dataset.adminPanel='disk';panel.innerHTML='<div class="admin-function-head"><button class="admin-function-back admin-disk-back" type="button" aria-label="Wróć">←</button><h2 class="admin-function-heading">Dysk</h2></div><section class="card"><h2>Wykorzystanie miejsca</h2><p class="small">Aktualne zużycie Supabase oraz repozytorium aplikacji.</p><div id="adminDiskContent">Ładowanie...</div><button id="adminDiskRefresh" class="secondary admin-disk-refresh" type="button">Odśwież</button></section>';dashboard.appendChild(panel);
tile.addEventListener('click',e=>{e.stopImmediatePropagation();m.hidden=true;document.querySelectorAll('.admin-function-panel').forEach(p=>p.classList.toggle('active',p===panel));history.replaceState(null,'','#admin-disk');load()});panel.querySelector('.admin-disk-back').onclick=e=>{e.stopPropagation();panel.classList.remove('active');m.hidden=false;history.replaceState(null,'',location.pathname+location.search);window.scrollTo({top:0,behavior:'smooth'})};panel.querySelector('#adminDiskRefresh').onclick=load}
async function githubSize(){try{const r=await fetch(`${GITHUB_REPO_API}?t=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw new Error('GitHub');const j=await r.json();return Number(j.size||0)*1024}catch(e){return null}}
async function load(){const host=document.getElementById('adminDiskContent');if(!host)return;host.textContent='Ładowanie...';try{const [sup,appBytes]=await Promise.all([sb.rpc('admin_get_storage_stats',{p_device_token:adminDevice}),githubSize()]);if(sup.error)throw sup.error;const s=sup.data||{},sp=pct(s.storage_used_bytes,s.storage_limit_bytes),dp=pct(s.database_used_bytes,s.database_limit_bytes),ap=appBytes===null?0:pct(appBytes,GITHUB_REPO_LIMIT);const appCard=appBytes===null?`<div class="admin-disk-card"><h3>🌐 Aplikacja</h3><div class="admin-disk-number">Brak danych</div><div class="admin-disk-sub">Nie udało się pobrać rozmiaru repozytorium GitHub.</div></div>`:`<div class="admin-disk-card"><h3>🌐 Aplikacja</h3><div class="admin-disk-number">${fmt(appBytes)}</div><div class="admin-disk-sub">repozytorium GitHub • zalecany limit ${fmt(GITHUB_REPO_LIMIT)}</div><div class="admin-disk-bar"><span style="width:${ap}%"></span></div><div class="admin-disk-sub">${ap.toFixed(2)}% z 1 GB</div></div>`;host.innerHTML=`<div class="admin-disk-grid">${appCard}<div class="admin-disk-card"><h3>📸 Zdjęcia i pliki</h3><div class="admin-disk-number">${fmt(s.storage_used_bytes)}</div><div class="admin-disk-sub">z ${fmt(s.storage_limit_bytes)} • zostało ${fmt(s.storage_remaining_bytes)}</div><div class="admin-disk-bar"><span style="width:${sp}%"></span></div><div class="admin-disk-sub">${sp.toFixed(2)}% wykorzystane</div></div><div class="admin-disk-card"><h3>🗄️ Baza aplikacji</h3><div class="admin-disk-number">${fmt(s.database_used_bytes)}</div><div class="admin-disk-sub">z ${fmt(s.database_limit_bytes)} • zostało ${fmt(s.database_remaining_bytes)}</div><div class="admin-disk-bar"><span style="width:${dp}%"></span></div><div class="admin-disk-sub">${dp.toFixed(2)}% wykorzystane</div></div></div><div class="admin-disk-breakdown">${(s.buckets||[]).map(b=>`<div class="admin-disk-row"><strong>${prettyBucket(b.bucket)}</strong><span>${fmt(b.bytes)}</span></div>`).join('')||'<div class="admin-disk-row"><strong>Brak plików</strong><span>0 B</span></div>'}</div><div class="admin-disk-note">Supabase: plan ${s.plan||'Free'}. Limity plików i bazy są liczone osobno. Aplikacja pokazuje rozmiar repozytorium GitHub i nie wlicza się do limitów Supabase.</div>`}catch(e){host.textContent=e.message||'Nie udało się pobrać danych.'}}
function watch(){ensure();const role=document.querySelector('.role-badge')?.textContent||'';if(tile)tile.hidden=/FOTOGRAF/i.test(role)}new MutationObserver(watch).observe(dashboard,{subtree:true,childList:true,attributes:true});setTimeout(watch,300);
})();