(()=>{
let host=null,toast=null,hideTimer=null,lastKey='',lastAt=0;
const icons={success:'✓',error:'!',warning:'!',info:'i'};
function cleanText(value){return String(value??'').replace(/\s+/g,' ').replace(/([.!?])([A-ZĄĆĘŁŃÓŚŹŻ])/g,'$1 $2').trim()}
function inferType(text,node=null){const s=cleanText(text).toLowerCase();if(/możesz wybrać maksymalnie|maksymalnie \d+|limit /.test(s))return'warning';if(node?.classList?.contains('error')||/nie udało|błąd|zablok|nie można|nieprawidł|odrzucon|brak uprawnień|spróbuj ponownie/.test(s))return'error';if(/✓|zapisane|zapisano|wysłane|wysłano|przyjęte|gotowe|włączone|test wysłany|sukces/.test(s))return'success';return'info'}
function ensure(){if(host&&toast)return;host=document.getElementById('h3ToastHost');if(!host){host=document.createElement('div');host.id='h3ToastHost';host.setAttribute('aria-live','polite');host.setAttribute('aria-atomic','true');document.body.appendChild(host)}toast=host.querySelector('.h3-toast');if(!toast){toast=document.createElement('div');toast.className='h3-toast info';toast.innerHTML='<span class="h3-toast-icon" aria-hidden="true">i</span><span class="h3-toast-text"></span>';host.appendChild(toast)}}
function hide(){if(!toast)return;toast.classList.remove('show')}
function show(text,options={}){text=cleanText(text);if(!text)return;const type=['success','error','warning','info'].includes(options.type)?options.type:inferType(text,options.source||null),now=Date.now(),key=`${type}|${text}`;if(key===lastKey&&now-lastAt<650)return;lastKey=key;lastAt=now;ensure();clearTimeout(hideTimer);toast.className=`h3-toast ${type}`;toast.querySelector('.h3-toast-icon').textContent=icons[type]||'i';toast.querySelector('.h3-toast-text').textContent=text;host.setAttribute('aria-live',type==='error'?'assertive':'polite');toast.classList.remove('show');void toast.offsetWidth;requestAnimationFrame(()=>toast.classList.add('show'));const duration=Number(options.duration)||Math.min(5200,Math.max(2800,2200+text.length*24));hideTimer=setTimeout(hide,duration)}
window.H3Toast={show,hide,success:(text,options={})=>show(text,{...options,type:'success'}),error:(text,options={})=>show(text,{...options,type:'error'}),warning:(text,options={})=>show(text,{...options,type:'warning'}),info:(text,options={})=>show(text,{...options,type:'info'})};
window.addEventListener('h3:toast',e=>{const d=e.detail||{};show(d.text??d.message??'',d)});
const nativeAlert=window.alert?.bind(window);window.__h3NativeAlert=nativeAlert;window.alert=message=>show(message,{type:'info',duration:4200});
const legacySelector='#contestMessage,#bugReportToast,[data-notification-result]';
function captureOne(node){if(!node)return;const el=node.nodeType===1?node:node.parentElement;if(!el)return;const targets=[];if(el.matches?.(legacySelector))targets.push(el);el.querySelectorAll?.(legacySelector).forEach(x=>targets.push(x));for(const target of targets){const text=cleanText(target.textContent);if(!text)continue;show(text,{type:inferType(text,target),source:target})}}
function captureExisting(){document.querySelectorAll(legacySelector).forEach(captureOne)}
function startObserver(){captureExisting();const observer=new MutationObserver(records=>{for(const r of records){captureOne(r.target);for(const n of r.addedNodes)captureOne(n)}});observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class','hidden']});window.addEventListener('pagehide',()=>observer.disconnect(),{once:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startObserver,{once:true});else startObserver();
})();
