(()=>{
const view=document.querySelector('[data-view="other"]');if(!view)return;
const list=view.querySelector('#otherTiles'),detail=view.querySelector('#otherDetail');if(!list||!detail)return;
const BUG_ID='__bug_report__';
let sending=false;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
function ensureTile(){if(list.querySelector(`[data-other-id="${BUG_ID}"]`))return;const b=document.createElement('button');b.type='button';b.className='other-tile bug-report-tile';b.dataset.otherId=BUG_ID;b.innerHTML='<span class="other-tile-icon">🐞</span><span><strong>Zgłoś błąd</strong><small>Coś nie działa? Daj nam znać</small></span><span class="other-chevron">›</span>';list.appendChild(b)}
function showForm(){list.hidden=true;detail.hidden=false;detail.dataset.currentId=BUG_ID;detail.innerHTML=`<button type="button" class="other-back">← Wróć</button><div class="other-detail bug-report-detail"><div class="other-detail-head"><span class="other-detail-icon">🐞</span><h2>Zgłoś błąd</h2></div><p class="bug-report-intro">Opisz, co się stało i co robiłeś chwilę wcześniej. Informacja o wersji aplikacji i urządzeniu zostanie dołączona automatycznie.</p><label class="bug-report-label" for="bugReportMessage">Opis błędu</label><textarea id="bugReportMessage" class="bug-report-textarea" maxlength="2000" rows="7" placeholder="Np. po wejściu w Zdjęcia i otwarciu fotografii przycisk reakcji nie działa..."></textarea><div class="bug-report-counter"><span data-bug-count>0</span> / 2000</div><button type="button" class="bug-report-submit" data-bug-submit>WYŚLIJ ZGŁOSZENIE</button></div>`;const ta=detail.querySelector('#bugReportMessage'),count=detail.querySelector('[data-bug-count]');ta?.focus?.({preventScroll:true});ta?.addEventListener('input',()=>{if(count)count.textContent=String(ta.value.length)})}
function toast(text,error=false){let t=document.getElementById('bugReportToast');if(!t){t=document.createElement('div');t.id='bugReportToast';t.className='bug-report-toast';document.body.appendChild(t)}t.textContent=text;t.classList.toggle('error',!!error);t.classList.remove('show');void t.offsetWidth;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),4200)}
function visitorId(){let v=window.H3Analytics?.visitorId||null;if(!v){try{v=localStorage.getItem('h3_visitor_id')}catch{}}return UUID.test(v||'')?v:null}
function context(){return window.H3Analytics?.context||(matchMedia('(display-mode: standalone)').matches?'pwa':'browser')}
async function currentVersion(){try{const r=await fetch(`./service-worker.js?bug-report-version=${Date.now()}`,{cache:'no-store'});if(!r.ok)return null;const txt=await r.text(),m=txt.match(/CACHE_NAME\s*=\s*['"]halloween-3-v(\d+)['"]/);return m?`V${m[1]}`:null}catch{return null}}
async function submit(){if(sending)return;const ta=detail.querySelector('#bugReportMessage'),btn=detail.querySelector('[data-bug-submit]');if(!ta||!btn)return;const message=ta.value.trim();if(message.length<5){toast('Opisz błąd trochę dokładniej.',true);ta.focus();return}sending=true;btn.disabled=true;btn.textContent='WYSYŁANIE...';try{const version=await currentVersion();const{error}=await sb.rpc('submit_app_bug_report',{p_visitor_id:visitorId(),p_message:message,p_context:context(),p_app_version:version,p_user_agent:navigator.userAgent||null});if(error)throw error;ta.value='';const c=detail.querySelector('[data-bug-count]');if(c)c.textContent='0';toast('Zgłoszenie wysłane. Dzięki! ✓');btn.textContent='WYSŁANO ✓';setTimeout(()=>{if(document.body.contains(btn)){btn.textContent='WYŚLIJ ZGŁOSZENIE';btn.disabled=false}},1800)}catch(e){console.warn('Bug report failed',e);toast(e.message||'Nie udało się wysłać zgłoszenia.',true);btn.textContent='WYŚLIJ ZGŁOSZENIE';btn.disabled=false}finally{sending=false}}
view.addEventListener('click',e=>{const tile=e.target.closest(`[data-other-id="${BUG_ID}"]`);if(tile){e.preventDefault();showForm();return}if(e.target.closest('[data-bug-submit]')){e.preventDefault();submit()}});
new MutationObserver(()=>{if(!detail.hidden&&detail.dataset.currentId===BUG_ID)return;ensureTile()}).observe(list,{childList:true});
document.querySelector('.nav-item[data-tab="other"]')?.addEventListener('click',()=>setTimeout(ensureTile,80));
setTimeout(ensureTile,300);
})();