(()=>{
let current=null;
function mount(host){unmount();if(!host)return;
 host.innerHTML='<div class="creepy-game-wrap"><div class="creepy-game-shell"><canvas class="creepy-game-canvas" width="360" height="560"></canvas><div class="creepy-game-overlay"><div class="creepy-game-card"><div class="creepy-game-title">Creepy Pumpkin</div><p>Leć przez nawiedzony cmentarz. Stuknij ekran, żeby podbić dynię.</p><button type="button" class="creepy-game-start">START</button></div></div></div><div class="creepy-game-stats"><span>Wynik: <strong class="creepy-score">0</strong></span><span>Rekord: <strong class="creepy-best">0</strong></span></div><div class="creepy-game-tip">Sterowanie: stuknij w grę. Im dalej, tym szybciej.</div></div>';
 const canvas=host.querySelector('canvas'),ctx=canvas.getContext('2d'),overlay=host.querySelector('.creepy-game-overlay'),startBtn=host.querySelector('.creepy-game-start'),scoreEl=host.querySelector('.creepy-score'),bestEl=host.querySelector('.creepy-best');
 let raf=0,running=false,dead=false,last=0,score=0,speed=115,spawn=0;let best=Number(localStorage.getItem('h3_creepy_pumpkin_best')||0);bestEl.textContent=best;
 const pumpkin={x:82,y:250,vy:0,r:18};let pipes=[];const stars=Array.from({length:40},()=>({x:Math.random()*360,y:Math.random()*430,s:Math.random()*1.7+.4,a:Math.random()*.7+.2}));
 function reset(){pumpkin.y=250;pumpkin.vy=0;pipes=[];score=0;speed=115;spawn=0;scoreEl.textContent='0';dead=false}
 function flap(){if(!running){start();return}pumpkin.vy=-285}
 function start(){reset();running=true;overlay.hidden=true;last=performance.now();raf=requestAnimationFrame(loop)}
 function gameOver(){running=false;dead=true;cancelAnimationFrame(raf);if(score>best){best=score;localStorage.setItem('h3_creepy_pumpkin_best',String(best));bestEl.textContent=best}overlay.hidden=false;overlay.querySelector('.creepy-game-title').textContent='Koniec gry';overlay.querySelector('p').innerHTML=`Wynik: <strong>${score}</strong><br>Rekord: <strong>${best}</strong>`;startBtn.textContent='JESZCZE RAZ';try{navigator.vibrate?.([40,30,70])}catch{}}
 function addPipe(){const gap=Math.max(120,158-score*1.2),top=70+Math.random()*260;pipes.push({x:380,w:58,top,gap,passed:false})}
 function hitPipe(p){const left=p.x,right=p.x+p.w,px=pumpkin.x,py=pumpkin.y,r=pumpkin.r-3;if(px+r<left||px-r>right)return false;return py-r<p.top||py+r>p.top+p.gap}
 function loop(t){if(!running)return;const dt=Math.min(.03,(t-last)/1000);last=t;pumpkin.vy+=720*dt;pumpkin.y+=pumpkin.vy*dt;spawn-=dt;if(spawn<=0){addPipe();spawn=Math.max(1.15,1.55-score*.012)}speed=115+Math.min(95,score*3.3);for(const p of pipes){p.x-=speed*dt;if(!p.passed&&p.x+p.w<pumpkin.x){p.passed=true;score++;scoreEl.textContent=score}}pipes=pipes.filter(p=>p.x>-80);if(pumpkin.y-pumpkin.r<0||pumpkin.y+pumpkin.r>510||pipes.some(hitPipe)){gameOver();draw();return}draw();raf=requestAnimationFrame(loop)}
 function drawBackground(){const g=ctx.createLinearGradient(0,0,0,560);g.addColorStop(0,'#13091d');g.addColorStop(.58,'#241026');g.addColorStop(1,'#080508');ctx.fillStyle=g;ctx.fillRect(0,0,360,560);ctx.fillStyle='rgba(255,241,190,.9)';ctx.beginPath();ctx.arc(292,82,36,0,Math.PI*2);ctx.fill();ctx.fillStyle='#13091d';ctx.beginPath();ctx.arc(307,73,34,0,Math.PI*2);ctx.fill();for(const s of stars){ctx.globalAlpha=s.a;ctx.fillStyle='#fff0d2';ctx.fillRect(s.x,s.y,s.s,s.s)}ctx.globalAlpha=1;ctx.fillStyle='#080508';for(let i=0;i<9;i++){const x=i*48-15,h=18+(i%3)*8;ctx.fillRect(x,486-h,34,h);ctx.beginPath();ctx.arc(x+17,486-h,17,Math.PI,0);ctx.fill()}ctx.fillStyle='#130b0e';ctx.fillRect(0,510,360,50);ctx.strokeStyle='#6d2c17';ctx.lineWidth=2;for(let x=0;x<360;x+=24){ctx.beginPath();ctx.moveTo(x,510);ctx.lineTo(x,560);ctx.stroke()}ctx.fillStyle='#0b070a';ctx.font='20px serif';ctx.fillText('🦇',46,92);ctx.fillText('🦇',170,132);ctx.font='16px serif';ctx.fillText('🦇',225,48)}
 function drawPipe(p){const grad=ctx.createLinearGradient(p.x,0,p.x+p.w,0);grad.addColorStop(0,'#1b0b13');grad.addColorStop(.5,'#321226');grad.addColorStop(1,'#16080f');ctx.fillStyle=grad;ctx.strokeStyle='#ff6817';ctx.lineWidth=2;ctx.shadowColor='rgba(255,80,10,.35)';ctx.shadowBlur=10;ctx.fillRect(p.x,0,p.w,p.top);ctx.strokeRect(p.x,0,p.w,p.top);const by=p.top+p.gap;ctx.fillRect(p.x,by,p.w,510-by);ctx.strokeRect(p.x,by,p.w,510-by);ctx.shadowBlur=0;ctx.fillStyle='#241020';for(let y=18;y<p.top-18;y+=32)ctx.fillRect(p.x+8,y,p.w-16,6);for(let y=by+18;y<500;y+=32)ctx.fillRect(p.x+8,y,p.w-16,6);ctx.font='20px serif';ctx.fillText('🕸️',p.x+4,p.top-8);ctx.fillText('🕸️',p.x+p.w-24,by+22)}
 function drawPumpkin(){ctx.save();ctx.translate(pumpkin.x,pumpkin.y);ctx.rotate(Math.max(-.35,Math.min(.45,pumpkin.vy/550)));ctx.shadowColor='rgba(255,106,0,.8)';ctx.shadowBlur=16;ctx.font='42px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('🎃',0,1);ctx.restore();ctx.shadowBlur=0}
 function draw(){drawBackground();for(const p of pipes)drawPipe(p);drawPumpkin();ctx.fillStyle='rgba(0,0,0,.28)';ctx.fillRect(0,0,360,42);ctx.fillStyle='#ff9b42';ctx.font='800 22px Inter,system-ui,sans-serif';ctx.textAlign='center';ctx.fillText(String(score),180,29)}
 canvas.addEventListener('pointerdown',e=>{e.preventDefault();flap()});startBtn.addEventListener('click',e=>{e.preventDefault();start()});draw();
 current={host,stop(){running=false;cancelAnimationFrame(raf)},toggleFullscreen(){const box=host.closest('.creepy-game-detail');if(!box)return;const active=box.classList.toggle('creepy-game-fullscreen-box');document.body.classList.toggle('creepy-game-fullscreen',active);const btn=box.querySelector('.creepy-fullscreen-button');if(btn){btn.textContent=active?'✕':'⛶';btn.setAttribute('aria-label',active?'Wyłącz pełny ekran':'Włącz pełny ekran');btn.title=active?'Wyłącz pełny ekran':'Pełny ekran'}},exitFullscreen(){const box=host.closest('.creepy-game-detail');box?.classList.remove('creepy-game-fullscreen-box');document.body.classList.remove('creepy-game-fullscreen')}};
}
function unmount(){if(current){current.exitFullscreen?.();current.stop();current=null}}
function toggleFullscreen(){current?.toggleFullscreen?.()}
window.CreepyPumpkinGame={mount,unmount,toggleFullscreen};
})();