(()=>{
const REACTIONS=['👍','❤️','😂','😮','🎃'];
function getReactionDevice(){let t=localStorage.getItem('h3_gallery_reaction_device');if(!t){t=crypto.randomUUID();localStorage.setItem('h3_gallery_reaction_device',t)}return t}
const reactionDevice=getReactionDevice();
let galleryData=[],reactionData=new Map(),decorateBusy=false,decorateTimer=null;
function escText(v=''){return String(v??'')}
function publicGalleryUrl(path){return `${SUPABASE_URL}/storage/v1/object/public/admin-gallery/${String(path||'').split('/').map(encodeURIComponent).join('/')}`}
async function loadNewsManaged(){const section=document.querySelector('[data-view="news"]');if(!section)return;try{const{data,error}=await sb.rpc('get_news_posts');if(error)throw error;section.querySelectorAll(':scope > article.content-card,:scope > .news-empty').forEach(x=>x.remove());const posts=data||[];if(!posts.length){const e=document.createElement('div');e.className='news-empty';e.textContent='Brak aktualności.';section.appendChild(e);return}posts.forEach((p,i)=>{const a=document.createElement('article');a.className='content-card news-managed'+(i===0?' featured-card':'');const icon=document.createElement('div');icon.className='card-icon';icon.textContent=p.icon||'🎃';const body=document.createElement('div');if(p.badge){const b=document.createElement('span');b.className='card-badge';b.textContent=p.badge;body.appendChild(b)}const h=document.createElement('h2');h.textContent=p.title||'';const txt=document.createElement('p');txt.textContent=p.body||'';body.append(h,txt);if((p.icon||'')==='🎰'||/losow/i.test((p.title||'')+' '+(p.body||''))){const btn=document.createElement('button');btn.className='text-action';btn.type='button';btn.textContent='Przejdź do losowania';btn.addEventListener('click',()=>{document.querySelector('.nav-item[data-tab="draw"]')?.click()});body.appendChild(btn)}a.append(icon,body);section.appendChild(a)})}catch(e){console.warn('News load failed',e)}}
function buildReactionBar(photoId,state){const bar=document.createElement('div');bar.className='photo-reactions';bar.dataset.photoId=photoId;renderReactionBar(bar,state);return bar}
function renderReactionBar(bar,state){bar.innerHTML='';for(const r of REACTIONS){const b=document.createElement('button');b.type='button';b.className='photo-reaction'+(state?.my_reaction===r?' active':'');b.dataset.reaction=r;b.innerHTML=`<span>${r}</span><span class="photo-reaction-count">${Number(state?.counts?.[r]||0)||''}</span>`;bar.appendChild(b)}}
async function setReaction(photoId,reaction,bar){const current=reactionData.get(photoId)||{my_reaction:null,counts:{}};const next=current.my_reaction===reaction?'':reaction;bar.querySelectorAll('button').forEach(b=>b.disabled=true);try{const{data,error}=await sb.rpc('set_gallery_photo_reaction',{p_photo_id:photoId,p_device_token:reactionDevice,p_reaction:next});if(error)throw error;reactionData.set(photoId,data);renderReactionBar(bar,data);syncViewerReactions(photoId,data)}catch(e){console.error(e)}finally{bar.querySelectorAll('button').forEach(b=>b.disabled=false)}}
async function refreshGalleryExtras(){if(decorateBusy)return;const showcase=document.getElementById('photoShowcase');if(!showcase||!document.body.contains(showcase))return;decorateBusy=true;try{const [{data:g,error:ge},{data:r,error:re}]=await Promise.all([sb.rpc('get_photo_gallery'),sb.rpc('get_gallery_photo_reactions',{p_device_token:reactionDevice})]);if(ge)throw ge;if(re)throw re;galleryData=g||[];reactionData=new Map((r||[]).map(x=>[x.photo_id,x]));const byUrl=new Map();for(const t of galleryData){for(const p of(t.photos||[]))byUrl.set(publicGalleryUrl(p.image_path),p)}showcase.querySelectorAll('.gallery-folder-grid img').forEach(img=>{const p=byUrl.get(img.src)||[...byUrl.entries()].find(([u])=>decodeURI(u)===decodeURI(img.src))?.[1];if(!p)return;let wrap=img.closest('.gallery-photo-item');if(!wrap){wrap=document.createElement('div');wrap.className='gallery-photo-item';img.parentNode.insertBefore(wrap,img);wrap.appendChild(img)}wrap.dataset.photoId=p.id;img.dataset.photoId=p.id;img.dataset.caption=p.caption||'';let bar=wrap.querySelector('.photo-reactions');if(!bar){bar=buildReactionBar(p.id,reactionData.get(p.id));wrap.appendChild(bar)}else renderReactionBar(bar,reactionData.get(p.id))})}catch(e){console.warn('Gallery extras failed',e)}finally{decorateBusy=false}}
function scheduleDecorate(){clearTimeout(decorateTimer);decorateTimer=setTimeout(refreshGalleryExtras,120)}
const showcase=document.getElementById('photoShowcase');if(showcase)new MutationObserver(scheduleDecorate).observe(showcase,{childList:true,subtree:true});
document.addEventListener('click',e=>{const rb=e.target.closest('.photo-reaction');if(rb){e.preventDefault();e.stopPropagation();const bar=rb.closest('.photo-reactions');setReaction(bar.dataset.photoId,rb.dataset.reaction,bar);return}const img=e.target.closest('.gallery-photo-item>img');if(img){e.preventDefault();openViewer(img)}});
document.querySelector('.nav-item[data-tab="photos"]')?.addEventListener('click',()=>setTimeout(scheduleDecorate,50));document.querySelector('.nav-item[data-tab="news"]')?.addEventListener('click',loadNewsManaged);
loadNewsManaged();
setTimeout(scheduleDecorate,300);

const viewer=document.createElement('div');viewer.id='photoViewer';viewer.className='photo-viewer';viewer.hidden=true;viewer.innerHTML='<div class="photo-viewer-top"><button class="photo-viewer-close" type="button" aria-label="Zamknij">×</button></div><div class="photo-viewer-stage"><img alt="Zdjęcie"></div><div class="photo-viewer-help">Przeciągnij, aby przesuwać. Użyj dwóch palców, aby przybliżać.</div>';
document.body.appendChild(viewer);const stage=viewer.querySelector('.photo-viewer-stage'),viewerImg=viewer.querySelector('img');let scale=1,x=0,y=0,lastTap=0;const pts=new Map();let pinchStartDist=0,pinchStartScale=1,startPan=null;
function applyTransform(){viewerImg.style.transform=`translate3d(${x}px,${y}px,0) scale(${scale})`}
function resetView(){scale=1;x=0;y=0;pts.clear();startPan=null;applyTransform()}
function openViewer(img){viewerImg.src=img.src;viewerImg.alt=img.alt||'Zdjęcie';viewer.dataset.photoId=img.dataset.photoId||'';resetView();viewer.hidden=false;document.body.style.overflow='hidden'}
function closeViewer(){viewer.hidden=true;viewerImg.removeAttribute('src');document.body.style.overflow='';resetView()}
viewer.querySelector('.photo-viewer-close').onclick=closeViewer;viewer.addEventListener('click',e=>{if(e.target===viewer)closeViewer()});
stage.addEventListener('pointerdown',e=>{stage.setPointerCapture?.(e.pointerId);pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.size===1)startPan={x:e.clientX,y:e.clientY,ox:x,oy:y};if(pts.size===2){const a=[...pts.values()];pinchStartDist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)||1;pinchStartScale=scale}const now=Date.now();if(now-lastTap<300&&pts.size===1){scale=scale>1?1:2;x=0;y=0;applyTransform()}lastTap=now},{passive:false});
stage.addEventListener('pointermove',e=>{if(!pts.has(e.pointerId))return;pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.size===2){const a=[...pts.values()];const d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)||1;scale=Math.max(1,Math.min(5,pinchStartScale*d/pinchStartDist));if(scale===1){x=0;y=0}applyTransform()}else if(pts.size===1&&scale>1&&startPan){x=startPan.ox+(e.clientX-startPan.x);y=startPan.oy+(e.clientY-startPan.y);applyTransform()}},{passive:false});
function endPointer(e){pts.delete(e.pointerId);if(pts.size===1){const p=[...pts.values()][0];startPan={x:p.x,y:p.y,ox:x,oy:y}}else if(!pts.size)startPan=null}
stage.addEventListener('pointerup',endPointer);stage.addEventListener('pointercancel',endPointer);stage.addEventListener('wheel',e=>{e.preventDefault();scale=Math.max(1,Math.min(5,scale*(e.deltaY<0?1.15:.87)));if(scale===1){x=0;y=0}applyTransform()},{passive:false});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!viewer.hidden)closeViewer()});
function syncViewerReactions(photoId,state){document.querySelectorAll(`.photo-reactions[data-photo-id="${CSS.escape(photoId)}"]`).forEach(bar=>renderReactionBar(bar,state))}
})();