(()=>{
const REACTIONS=['👍','❤️','😂','😮','🎃'];
function getReactionDevice(){let t=localStorage.getItem('h3_gallery_reaction_device');if(!t){t=crypto.randomUUID();localStorage.setItem('h3_gallery_reaction_device',t)}return t}
const reactionDevice=getReactionDevice();
let galleryData=[],reactionData=new Map(),decorateBusy=false,decorateTimer=null;
function escText(v=''){return String(v??'')}
function publicGalleryUrl(path){return `${SUPABASE_URL}/storage/v1/object/public/admin-gallery/${String(path||'').split('/').map(encodeURIComponent).join('/')}`}
function publicNewsImage(path){return `${SUPABASE_URL}/storage/v1/object/public/news-images/${String(path||'').split('/').map(encodeURIComponent).join('/')}`}
function fallbackRich(value=''){const raw=String(value??'');if(!/<\/?(?:b|strong|i|em|u|s|br|p|div|ul|ol|li)\b/i.test(raw)){const d=document.createElement('div');d.textContent=raw;return d.innerHTML.replace(/\r?\n/g,'<br>')}const doc=new DOMParser().parseFromString(raw,'text/html'),allowed=new Set(['B','STRONG','I','EM','U','S','BR','P','DIV','UL','OL','LI']),drop=new Set(['SCRIPT','STYLE','META','LINK','IFRAME','OBJECT','EMBED','IMG','SVG','CANVAS','FORM','INPUT','BUTTON']);function unwrap(el){const p=el.parentNode;if(!p)return;while(el.firstChild)p.insertBefore(el.firstChild,el);p.removeChild(el)}function walk(parent){[...parent.childNodes].forEach(n=>{if(n.nodeType===3)return;if(n.nodeType!==1){n.remove();return}if(drop.has(n.tagName)){n.remove();return}walk(n);if(allowed.has(n.tagName)){[...n.attributes].forEach(a=>n.removeAttribute(a.name))}else unwrap(n)})}walk(doc.body);return doc.body.innerHTML}
function richHtml(value=''){return window.H3RichText?.render?window.H3RichText.render(value):fallbackRich(value)}
function makeNewsBody(value){const body=document.createElement('div');body.className='news-full-text rich-content';body.innerHTML=richHtml(value);return body}
async function loadNewsManaged(){const section=document.querySelector('[data-view="news"]');if(!section)return;try{const{data,error}=await sb.rpc('get_news_posts');if(error)throw error;const posts=data||[],fragment=document.createDocumentFragment();if(!posts.length){const e=document.createElement('div');e.className='news-empty';e.textContent='Brak aktualności.';fragment.appendChild(e)}else posts.forEach((p,i)=>{const a=document.createElement('article'),hasImage=!!p.image_path;a.className='content-card news-managed'+(i===0?' featured-card':'')+(hasImage?' news-with-image':'');a.dataset.newsId=p.id||'';const copy=document.createElement('div');copy.className='news-post-copy';if(p.badge){const b=document.createElement('span');b.className='card-badge';b.textContent=p.badge;copy.appendChild(b)}const h=document.createElement('h2');h.textContent=p.title||'';copy.appendChild(h);const richBody=makeNewsBody(p.body||'');let action=null;if((p.icon||'')==='🎰'){action=document.createElement('button');action.className='text-action';action.type='button';action.textContent='Przejdź do losowania';action.addEventListener('click',()=>document.querySelector('.nav-item[data-tab="draw"]')?.click())}if(hasImage){copy.appendChild(richBody);a.appendChild(copy);if(action)a.appendChild(action);const img=document.createElement('img');img.className='news-post-image';img.src=publicNewsImage(p.image_path);img.alt=p.title||'Zdjęcie aktualności';img.loading='lazy';a.appendChild(img)}else{const head=document.createElement('div');head.className='news-layout-head';const icon=document.createElement('div');icon.className='card-icon';icon.textContent=p.icon||'🎃';head.append(icon,copy);a.append(head,richBody);if(action)a.appendChild(action)}fragment.appendChild(a)});section.querySelectorAll(':scope > article.content-card,:scope > .news-empty').forEach(x=>x.remove());section.appendChild(fragment);window.dispatchEvent(new CustomEvent('h3:news-rendered'))}catch(e){console.warn('News load failed',e)}}
window.loadNewsManaged=loadNewsManaged;
function buildReactionUI(photoId,state){const shell=document.createElement('div');shell.className='photo-reaction-ui';shell.dataset.photoId=photoId;const menu=document.createElement('div');menu.className='photo-reactions';menu.hidden=true;const toggle=document.createElement('button');toggle.type='button';toggle.className='photo-reaction-toggle';toggle.setAttribute('aria-label','Dodaj reakcję');toggle.setAttribute('aria-expanded','false');shell.append(menu,toggle);renderReactionUI(shell,state);return shell}
function renderReactionUI(shell,state){const menu=shell.querySelector('.photo-reactions'),toggle=shell.querySelector('.photo-reaction-toggle');menu.innerHTML='';for(const r of REACTIONS){const b=document.createElement('button');b.type='button';b.className='photo-reaction'+(state?.my_reaction===r?' active':'');b.dataset.reaction=r;const count=Number(state?.counts?.[r]||0);b.innerHTML=`<span class="photo-reaction-emoji">${r}</span>${count?`<span class="photo-reaction-count">${count}</span>`:''}`;menu.appendChild(b)}toggle.textContent=state?.my_reaction||'+';toggle.classList.toggle('has-reaction',!!state?.my_reaction)}
function closeAllReactionMenus(except=null){document.querySelectorAll('.photo-reaction-ui.open').forEach(ui=>{if(ui===except)return;ui.classList.remove('open');const m=ui.querySelector('.photo-reactions'),t=ui.querySelector('.photo-reaction-toggle');if(m)m.hidden=true;if(t)t.setAttribute('aria-expanded','false')})}
async function setReaction(photoId,reaction,shell){const current=reactionData.get(photoId)||{my_reaction:null,counts:{}};const next=current.my_reaction===reaction?'':reaction;shell.querySelectorAll('button').forEach(b=>b.disabled=true);try{const{data,error}=await sb.rpc('set_gallery_photo_reaction',{p_photo_id:photoId,p_device_token:reactionDevice,p_reaction:next});if(error)throw error;reactionData.set(photoId,data);renderReactionUI(shell,data);syncViewerReactions(photoId,data);shell.classList.remove('open');shell.querySelector('.photo-reactions').hidden=true;shell.querySelector('.photo-reaction-toggle').setAttribute('aria-expanded','false')}catch(e){console.error(e)}finally{shell.querySelectorAll('button').forEach(b=>b.disabled=false)}}
async function refreshGalleryExtras(){if(decorateBusy)return;const showcase=document.getElementById('photoShowcase');if(!showcase||!document.body.contains(showcase))return;decorateBusy=true;try{const [{data:g,error:ge},{data:r,error:re}]=await Promise.all([sb.rpc('get_photo_gallery'),sb.rpc('get_gallery_photo_reactions',{p_device_token:reactionDevice})]);if(ge)throw ge;if(re)throw re;galleryData=g||[];reactionData=new Map((r||[]).map(x=>[x.photo_id,x]));const byUrl=new Map();for(const t of galleryData){for(const p of(t.photos||[]))byUrl.set(publicGalleryUrl(p.image_path),p)}showcase.querySelectorAll('.gallery-folder-grid img').forEach(img=>{const p=byUrl.get(img.src)||[...byUrl.entries()].find(([u])=>decodeURI(u)===decodeURI(img.src))?.[1];if(!p)return;let wrap=img.closest('.gallery-photo-item');if(!wrap){wrap=document.createElement('div');wrap.className='gallery-photo-item';img.parentNode.insertBefore(wrap,img);wrap.appendChild(img)}wrap.dataset.photoId=p.id;img.dataset.photoId=p.id;img.dataset.caption=p.caption||'';let ui=wrap.querySelector('.photo-reaction-ui');if(!ui){ui=buildReactionUI(p.id,reactionData.get(p.id));wrap.appendChild(ui)}else renderReactionUI(ui,reactionData.get(p.id))})}catch(e){console.warn('Gallery extras failed',e)}finally{decorateBusy=false}}
function scheduleDecorate(){clearTimeout(decorateTimer);decorateTimer=setTimeout(refreshGalleryExtras,120)}
const showcase=document.getElementById('photoShowcase');if(showcase)new MutationObserver(scheduleDecorate).observe(showcase,{childList:true,subtree:true});
document.addEventListener('click',e=>{const choice=e.target.closest('.photo-reaction');if(choice){e.preventDefault();e.stopPropagation();const shell=choice.closest('.photo-reaction-ui');setReaction(shell.dataset.photoId,choice.dataset.reaction,shell);return}const toggle=e.target.closest('.photo-reaction-toggle');if(toggle){e.preventDefault();e.stopPropagation();const shell=toggle.closest('.photo-reaction-ui'),menu=shell.querySelector('.photo-reactions'),willOpen=!shell.classList.contains('open');closeAllReactionMenus(shell);shell.classList.toggle('open',willOpen);menu.hidden=!willOpen;toggle.setAttribute('aria-expanded',String(willOpen));return}if(!e.target.closest('.photo-reaction-ui'))closeAllReactionMenus();const img=e.target.closest('.gallery-photo-item>img');if(img){e.preventDefault();openViewer(img)}});
document.querySelector('.nav-item[data-tab="photos"]')?.addEventListener('click',()=>setTimeout(scheduleDecorate,50));document.querySelector('.nav-item[data-tab="news"]')?.addEventListener('click',loadNewsManaged);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&document.querySelector('[data-view="news"]')?.classList.contains('active'))loadNewsManaged()});window.addEventListener('pageshow',e=>{if(e.persisted&&document.querySelector('[data-view="news"]')?.classList.contains('active'))loadNewsManaged()});
loadNewsManaged();setTimeout(scheduleDecorate,300);
const viewer=document.createElement('div');viewer.id='photoViewer';viewer.className='photo-viewer';viewer.hidden=true;viewer.innerHTML='<div class="photo-viewer-top"><button class="photo-viewer-close" type="button" aria-label="Zamknij">×</button></div><div class="photo-viewer-stage"><img alt="Zdjęcie"></div><div class="photo-viewer-help">Przeciągnij, aby przesuwać. Użyj dwóch palców, aby przybliżać.</div>';document.body.appendChild(viewer);const stage=viewer.querySelector('.photo-viewer-stage'),viewerImg=viewer.querySelector('img');let scale=1,x=0,y=0,lastTap=0;const pts=new Map();let pinchStartDist=0,pinchStartScale=1,startPan=null;function applyTransform(){viewerImg.style.transform=`translate3d(${x}px,${y}px,0) scale(${scale})`}function resetView(){scale=1;x=0;y=0;pts.clear();startPan=null;applyTransform()}function openViewer(img){viewerImg.src=img.src;viewerImg.alt=img.alt||'Zdjęcie';viewer.dataset.photoId=img.dataset.photoId||'';resetView();viewer.hidden=false;document.body.style.overflow='hidden'}function closeViewer(){viewer.hidden=true;viewerImg.removeAttribute('src');document.body.style.overflow='';resetView()}viewer.querySelector('.photo-viewer-close').onclick=closeViewer;viewer.addEventListener('click',e=>{if(e.target===viewer)closeViewer()});stage.addEventListener('pointerdown',e=>{stage.setPointerCapture?.(e.pointerId);pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.size===1)startPan={x:e.clientX,y:e.clientY,ox:x,oy:y};if(pts.size===2){const a=[...pts.values()];pinchStartDist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)||1;pinchStartScale=scale}const now=Date.now();if(now-lastTap<300&&pts.size===1){scale=scale>1?1:2;x=0;y=0;applyTransform()}lastTap=now},{passive:false});stage.addEventListener('pointermove',e=>{if(!pts.has(e.pointerId))return;pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.size===2){const a=[...pts.values()];const d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)||1;scale=Math.max(1,Math.min(5,pinchStartScale*d/pinchStartDist));if(scale===1){x=0;y=0}applyTransform()}else if(pts.size===1&&scale>1&&startPan){x=startPan.ox+(e.clientX-startPan.x);y=startPan.oy+(e.clientY-startPan.y);applyTransform()}},{passive:false});function endPointer(e){pts.delete(e.pointerId);if(pts.size===1){const p=[...pts.values()][0];startPan={x:p.x,y:p.y,ox:x,oy:y}}else if(!pts.size)startPan=null}stage.addEventListener('pointerup',endPointer);stage.addEventListener('pointercancel',endPointer);stage.addEventListener('wheel',e=>{e.preventDefault();scale=Math.max(1,Math.min(5,scale*(e.deltaY<0?1.15:.87)));if(scale===1){x=0;y=0}applyTransform()},{passive:false});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!viewer.hidden)closeViewer()});function syncViewerReactions(photoId,state){document.querySelectorAll(`.photo-reaction-ui[data-photo-id="${CSS.escape(photoId)}"]`).forEach(shell=>renderReactionUI(shell,state))}
})();