(()=>{
const ua=navigator.userAgent||'';
const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
const isChrome=/Chrome\/\d+/i.test(ua)&&!/EdgA|EdgiOS|OPR|SamsungBrowser|FBAN|FBAV|FB_IAB|Messenger|Instagram/i.test(ua);
const isAndroid=/Android/i.test(ua);
const installCard=document.getElementById('chromeInstallCard'),browserCard=document.getElementById('openChromeCard'),installedCard=document.getElementById('installedCard'),installBtn=document.getElementById('installNowButton'),chromeBtn=document.getElementById('openChromeButton'),openAppBtn=document.getElementById('openInstalledAppButton'),status=document.getElementById('installStatus');
let deferredPrompt=null,waiters=[];
function show(el){[installCard,browserCard,installedCard].forEach(x=>x.hidden=x!==el)}
function resolvePrompt(){waiters.splice(0).forEach(r=>r())}
async function isInstalled(){if(standalone)return true;try{if(typeof navigator.getInstalledRelatedApps==='function'){const apps=await navigator.getInstalledRelatedApps();if(Array.isArray(apps)&&apps.some(a=>a.platform==='webapp'))return true}}catch(e){console.warn('Installed app detection failed',e)}return false}
function appTarget(){const u=new URL('../',location.href);const src=new URL(location.href);['h3id','h3s'].forEach(k=>{const v=src.searchParams.get(k);if(v)u.searchParams.set(k,v)});return u}
function openInstalledApp(){window.H3Analytics?.track?.('install_open_app_click',{android:isAndroid});const target=appTarget();if(isAndroid){const fallback=encodeURIComponent(target.href);location.href=`intent://${target.host}${target.pathname}${target.search}${target.hash}#Intent;scheme=https;action=android.intent.action.VIEW;category=android.intent.category.BROWSABLE;S.browser_fallback_url=${fallback};end`;return}window.open(target.href,'_blank','noopener')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;resolvePrompt();if(isChrome&&!standalone)show(installCard)});
window.addEventListener('appinstalled',()=>{deferredPrompt=null;show(installedCard);window.H3Analytics?.track?.('install_landing_installed',{source:'install_page'})});
async function waitForPrompt(ms=3500){if(deferredPrompt)return true;await new Promise(resolve=>{let done=false;const finish=()=>{if(done)return;done=true;resolve()};waiters.push(finish);setTimeout(finish,ms)});return !!deferredPrompt}
async function install(){installBtn.disabled=true;installBtn.textContent='URUCHAMIANIE INSTALATORA…';status.textContent='Przygotowuję instalację…';window.H3Analytics?.track?.('install_landing_click',{browser:'chrome'});try{if(await isInstalled()){show(installedCard);return}const ready=await waitForPrompt();if(!ready){if(await isInstalled()){show(installedCard);return}status.textContent='Chrome nie udostępnił instalatora. Otwórz menu ⋮ i wybierz „Zainstaluj aplikację”.';installBtn.textContent='SPRÓBUJ PONOWNIE';return}const prompt=deferredPrompt;deferredPrompt=null;await prompt.prompt();const result=await prompt.userChoice;if(result?.outcome==='accepted'){status.textContent='Instalowanie aplikacji…';installBtn.textContent='INSTALOWANIE…';setTimeout(async()=>{if(await isInstalled())show(installedCard)},1800)}else{status.textContent='Instalacja została anulowana.';installBtn.textContent='ZAINSTALUJ APLIKACJĘ'}}catch(e){console.warn(e);status.textContent='Nie udało się uruchomić instalatora Chrome.';installBtn.textContent='SPRÓBUJ PONOWNIE'}finally{installBtn.disabled=false}}
function openChrome(){window.H3Analytics?.track?.('install_open_chrome_click',{source:/FBAN|FBAV|FB_IAB|Messenger/i.test(ua)?'messenger':'other_browser'});if(isAndroid){const target=location.host+location.pathname+location.search;location.href=`intent://${target}#Intent;scheme=https;package=com.android.chrome;S.browser_fallback_url=${encodeURIComponent(location.href)};end`;return}navigator.clipboard?.writeText(location.href).catch(()=>{});chromeBtn.textContent='LINK SKOPIOWANY';setTimeout(()=>chromeBtn.textContent='OTWÓRZ W CHROME',1800)}
installBtn?.addEventListener('click',install);chromeBtn?.addEventListener('click',openChrome);openAppBtn?.addEventListener('click',openInstalledApp);
(async()=>{if(await isInstalled()){show(installedCard);window.H3Analytics?.track?.('install_landing_open',{browser:isChrome?'chrome':'other',android:isAndroid,installed:true});return}if(isChrome)show(installCard);else show(browserCard);window.H3Analytics?.track?.('install_landing_open',{browser:isChrome?'chrome':'other',android:isAndroid,installed:false})})();
})();