(()=>{
const TABS=new Set(['news','draw','photos','contest','other']);
let handlingKey='';
function parseTarget(raw){try{const u=new URL(raw||location.href,location.href),tabRaw=u.searchParams.get('h3tab')||u.hash.replace(/^#/,'')||'news',tab=TABS.has(tabRaw)?tabRaw:'news',newsId=u.searchParams.get('h3news')||'',otherId=u.searchParams.get('h3other')||'',folderId=u.searchParams.get('h3folder')||'',campaignId=u.searchParams.get('h3push')||'';return{tab,newsId,otherId,folderId,campaignId,key:`${tab}|${newsId}|${otherId}|${folderId}|${campaignId}`}}catch{return{tab:'news',newsId:'',otherId:'',folderId:'',campaignId:'',key:'news||||'}}}
function openTab(tab){const btn=document.querySelector(`.nav-item[data-tab="${CSS.escape(tab)}"]`);if(btn){btn.click();return true}return false}
async function waitFor(selector,attempts=48,delay=125){for(let i=0;i<attempts;i++){const el=document.querySelector(selector);if(el)return el;await new Promise(r=>setTimeout(r,delay))}return null}
async function focusNews(newsId){if(!newsId)return;let posts=[];try{const{data,error}=await sb.rpc('get_news_posts');if(!error)posts=data||[]}catch{}for(let i=0;i<40;i++){const cards=[...document.querySelectorAll('.news-managed')];if(posts.length&&cards.length){cards.forEach((card,index)=>{const id=posts[index]?.id||'';if(id)card.dataset.newsId=id})}const article=document.querySelector(`.news-managed[data-news-id="${CSS.escape(newsId)}"]`);if(article){article.scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'});article.animate?.([{transform:'scale(1)'},{transform:'scale(1.015)'},{transform:'scale(1)'}],{duration:520,easing:'ease-out'});return}await new Promise(r=>setTimeout(r,125))}}
async function focusOther(otherId){if(!otherId)return;let parentId='';if(!otherId.startsWith('__')){try{const{data,error}=await sb.rpc('get_other_tiles');if(!error){for(const root of data||[]){if(String(root.id)===otherId)break;const child=(root.children||[]).find(x=>String(x.id)===otherId);if(child){parentId=String(root.id);break}}}}catch{}}if(parentId){const parent=await waitFor(`[data-other-id="${CSS.escape(parentId)}"]`);if(!parent)return;parent.click();await new Promise(r=>setTimeout(r,100));const child=await waitFor(`[data-other-id="${CSS.escape(otherId)}"]`);if(child){child.click();child.scrollIntoView?.({behavior:'smooth',block:'center'})}return}const item=await waitFor(`[data-other-id="${CSS.escape(otherId)}"]`);if(item){item.click();setTimeout(()=>{const detail=document.getElementById('otherDetail');if(detail&&!detail.hidden)detail.scrollIntoView({behavior:'smooth',block:'start'})},120)}}
async function focusFolder(folderId){if(!folderId)return;let folders=[];try{const{data,error}=await sb.rpc('get_photo_gallery');if(!error)folders=(data||[]).filter(x=>x.type==='folder')}catch{}for(let i=0;i<48;i++){const cards=[...document.querySelectorAll('.gallery-tile.folder-tile')];if(cards.length&&folders.length)cards.forEach((card,index)=>{const id=folders[index]?.id||'';if(id)card.dataset.galleryId=id});const folder=document.querySelector(`.gallery-tile.folder-tile[data-gallery-id="${CSS.escape(folderId)}"]`);if(folder){folder.scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'});folder.animate?.([{transform:'scale(1)'},{transform:'scale(1.012)'},{transform:'scale(1)'}],{duration:520,easing:'ease-out'});return}await new Promise(r=>setTimeout(r,125))}}
async function handle(raw){const t=parseTarget(raw);if(t.key===handlingKey)return;handlingKey=t.key;for(let i=0;i<20&&!openTab(t.tab);i++)await new Promise(r=>setTimeout(r,100));if(t.tab==='news'&&t.newsId){await new Promise(r=>setTimeout(r,120));await focusNews(t.newsId)}else if(t.tab==='other'&&t.otherId){await new Promise(r=>setTimeout(r,120));await focusOther(t.otherId)}else if(t.tab==='photos'&&t.folderId){await new Promise(r=>setTimeout(r,120));await focusFolder(t.folderId)}if(t.campaignId)window.H3Analytics?.track?.('push_target_open',{campaign_id:t.campaignId,target_tab:t.tab,news_id:t.newsId||null,other_id:t.otherId||null,folder_id:t.folderId||null})}
function initial(){const u=new URL(location.href);if(['h3push','h3tab','h3news','h3other','h3folder'].some(k=>u.searchParams.has(k)))setTimeout(()=>handle(location.href),300)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initial,{once:true});else initial();
navigator.serviceWorker?.addEventListener('message',e=>{if(e.data?.type==='H3_NOTIFICATION_OPEN')handle(e.data.url||location.href)});
})();