(()=>{
const ALLOWED=new Set(['B','STRONG','I','EM','U','S','BR','P','DIV','UL','OL','LI']);
const DROP=new Set(['SCRIPT','STYLE','META','LINK','IFRAME','OBJECT','EMBED','IMG','SVG','CANVAS','FORM','INPUT','BUTTON']);
function esc(v=''){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}
function semanticTags(el){const s=el.getAttribute?.('style')||'',out=[];if(/font-weight\s*:\s*(?:bold|[6-9]00)/i.test(s))out.push('strong');if(/font-style\s*:\s*italic/i.test(s))out.push('em');if(/text-decoration(?:-line)?\s*:[^;]*underline/i.test(s))out.push('u');if(/text-decoration(?:-line)?\s*:[^;]*line-through/i.test(s))out.push('s');return out}
function wrapChildren(doc,el,tags){if(!tags.length)return;let node=doc.createDocumentFragment();while(el.firstChild)node.appendChild(el.firstChild);for(const tag of tags){const w=doc.createElement(tag);w.appendChild(node);node=w}el.appendChild(node)}
function unwrap(el){const p=el.parentNode;if(!p)return;while(el.firstChild)p.insertBefore(el.firstChild,el);p.removeChild(el)}
function sanitize(input=''){const doc=new DOMParser().parseFromString(String(input??''),'text/html'),root=doc.body;if(!root)return '';function walk(parent){[...parent.childNodes].forEach(n=>{if(n.nodeType===3)return;if(n.nodeType!==1){n.remove();return}if(DROP.has(n.tagName)){n.remove();return}walk(n);wrapChildren(doc,n,semanticTags(n));if(ALLOWED.has(n.tagName)){[...n.attributes].forEach(a=>n.removeAttribute(a.name));return}unwrap(n)})}walk(root);let html=root.innerHTML.trim();const probe=doc.createElement('div');probe.innerHTML=html;if(!probe.textContent.trim())html='';return html}
function plainToHtml(v=''){return esc(String(v??'').replace(/\r\n?/g,'\n')).replace(/\n/g,'<br>')}
function render(stored=''){const s=String(stored??'');if(!s)return '';const looksRich=/<\/?(?:b|strong|i|em|u|s|br|p|div|ul|ol|li)\b/i.test(s);return looksRich?sanitize(s):plainToHtml(s)}
function toPlain(stored=''){const box=document.createElement('div');box.innerHTML=render(stored);let out='';try{out=box.innerText}catch{out=box.textContent||''}return String(out||'').replace(/\n{3,}/g,'\n\n').trim()}
function insertHtml(editor,html){const sel=window.getSelection?.();if(!sel||!sel.rangeCount||!editor.contains(sel.anchorNode)){editor.insertAdjacentHTML('beforeend',html);return}const range=sel.getRangeAt(0);range.deleteContents();const box=document.createElement('div');box.innerHTML=html;const frag=document.createDocumentFragment();let last=null;while(box.firstChild){last=box.firstChild;frag.appendChild(box.firstChild)}range.insertNode(frag);if(last){range.setStartAfter(last);range.collapse(true);sel.removeAllRanges();sel.addRange(range)}}
function hideBackingTextarea(textarea){textarea.dataset.richReady='1';textarea.hidden=true;textarea.tabIndex=-1;textarea.setAttribute('aria-hidden','true');textarea.style.setProperty('display','none','important');textarea.style.setProperty('visibility','hidden','important');textarea.style.setProperty('position','absolute','important');textarea.style.setProperty('width','1px','important');textarea.style.setProperty('height','1px','important');textarea.style.setProperty('overflow','hidden','important');textarea.style.setProperty('pointer-events','none','important')}
function enhanceTextarea(textarea){if(!textarea||textarea.dataset.richReady==='1')return textarea?._h3RichEditor||null;const editor=document.createElement('div');editor.className='h3-rich-editor';editor.contentEditable='true';editor.setAttribute('role','textbox');editor.setAttribute('aria-multiline','true');editor.setAttribute('spellcheck','true');editor.dataset.placeholder=textarea.getAttribute('placeholder')||'Wpisz treść';editor.innerHTML=render(textarea.value);hideBackingTextarea(textarea);textarea._h3RichEditor=editor;const parent=textarea.parentElement;if(parent?.tagName==='LABEL')parent.insertAdjacentElement('afterend',editor);else textarea.insertAdjacentElement('afterend',editor);
 function sync(){let html=sanitize(editor.innerHTML);textarea.value=html;return html}
 function normalize(){const html=sync();if(editor.innerHTML!==html)editor.innerHTML=html;return html}
 editor.addEventListener('input',sync);
 editor.addEventListener('paste',e=>{const html=e.clipboardData?.getData('text/html')||'';if(html){e.preventDefault();insertHtml(editor,sanitize(html));sync();return}setTimeout(normalize,0)});
 editor.addEventListener('blur',normalize);
 sync();return editor}
function enhanceAll(nodes){[...(nodes||[])].forEach(enhanceTextarea)}
function setValue(textarea,value=''){if(!textarea)return;textarea.value=String(value??'');if(textarea._h3RichEditor)textarea._h3RichEditor.innerHTML=render(textarea.value)}
window.H3RichText={sanitize,render,toPlain,enhanceTextarea,enhanceAll,setValue};
})();